import type { Capsule } from "./data";

// YKS'de çıkmış / sık sorulan soru kalıplarını temel alan, detaylı ve sınav odaklı kapsüller
export const extraCapsules4: Capsule[] = [
  // ===== TÜRKÇE =====
  {
    id: "yt1",
    category: "turkce",
    title: "Paragrafta Anlam Bütünlüğü (Cümle Yerleştirme)",
    summary: "YKS'de en çok soru gelen tür: bir cümlenin paragrafa uygun yere yerleştirilmesi veya akışı bozan cümlenin bulunması.",
    detail: "TYT Türkçe'nin yaklaşık yarısı paragraf sorularıdır ve bu soru tipi neredeyse her yıl 2-3 kez çıkar. 'Cümle yerleştirme' sorularında verilen cümledeki 'bu, o, bunun için, ancak, ayrıca' gibi bağlayıcılara bakılır; bu ifadeler cümlenin kendinden önceki bir düşünceye bağlandığını gösterir. 'Akışı bozan cümle' sorularında ise paragrafın konusundan sapan, farklı bir düşünceye geçen cümle işaretlenir. 'Paragrafı ikiye bölme' sorularında konunun/bakış açısının değiştiği nokta aranır. Anahtar strateji: numaralı cümleler arasındaki anlam köprülerini (zamir, bağlaç, ortak sözcük) takip etmektir.",
    funFact: "Yerleştirilecek cümle 'Oysa, ancak, buna karşın' ile başlıyorsa, kendinden önceki cümleyle ZIT bir yargı taşır; doğru yeri bulmak için önündeki boşluğa bu zıtlığın uyup uymadığına bak.",
    tags: ["paragraf", "cümle yerleştirme", "anlam bütünlüğü", "TYT"],
    difficulty: "Orta",
  },
  {
    id: "yt2",
    category: "turkce",
    title: "Fiilimsiler ve Cümlede Görevi (Çıkmış Soru Tipi)",
    summary: "Fiilimsinin türünü (isim/sıfat/zarf-fiil) ve cümledeki görevini sorma, YKS'nin klasik dil bilgisi sorusudur.",
    detail: "Fiilimsiler fiilden türeyip cümlede isim, sıfat veya zarf görevi üstlenen sözcüklerdir ve YKS'de hem dil bilgisi hem cümlenin ögeleri sorularında karşımıza çıkar. İsim-fiil (-mak, -ma, -ış): 'Yüzmek sağlıklıdır'. Sıfat-fiil (-an, -ası, -mez, -ar, -dik, -ecek, -miş): 'Gelen misafir' — bir ismi niteler. Zarf-fiil/bağ-fiil (-ip, -erek, -ince, -ken, -dikçe, -meden): 'Koşarak geldi' — fiili niteler. Çıkmış sorularda en sık istenen: verilen cümlede kaç fiilimsi olduğunu saymak veya farklı türde fiilimsi içeren cümleyi bulmaktır. Fiilimsi bulunan cümle en az iki yüklem taşır, yani basit cümle değildir.",
    funFact: "Tuzak: '-ma/-me' hem isim-fiil eki (okuma) hem olumsuzluk eki (gelmemek) olabilir. 'Bu okuma çok yararlı' (isim-fiil) ile 'Okumama izin ver' (isim-fiil + iyelik) ayrımına dikkat et; olumsuzluk ekiyle karıştırma.",
    tags: ["fiilimsi", "cümle bilgisi", "dil bilgisi", "TYT"],
    difficulty: "İleri",
  },
  {
    id: "yt3",
    category: "turkce",
    title: "Cümlede Anlam İlişkileri (Koşul, Karşılaştırma, Tanım)",
    summary: "YKS'de bir cümlenin hangi anlam ilişkisini taşıdığını sorma sık çıkar: koşul, karşılaştırma, tanımlama, öneri.",
    detail: "Cümlede anlam soruları YKS Türkçe'nin değişmez konusudur. Koşul (şart): '-se, -dikçe, -mek şartıyla' → 'Çalışırsan kazanırsın'. Karşılaştırma: 'göre, kadar, en, daha' → iki varlık/kavram kıyaslanır. Tanımlama: 'nedir?' sorusuna cevap verir → 'Roman, olayları geniş anlatan türdür'. Öneri: 'meli/malı, -sa iyi olur' → yol gösterir. Ayrıca varsayım ('diyelim ki'), olasılık ('belki, olabilir'), tahmin ('galiba'), eşitlik/beklenti gibi ilişkiler de sorulur. Bu soruların çözümünde cümledeki anahtar sözcükleri (bağlaç ve edatları) tespit etmek belirleyicidir.",
    funFact: "Karşılaştırma cümlesi her zaman 'üstünlük' bildirmez; 'Ali de kardeşi kadar çalışkandır' cümlesi eşitlik bildiren bir karşılaştırmadır. Seçeneklerdeki 'daha üstün' ifadesine kanma.",
    tags: ["cümlede anlam", "koşul", "karşılaştırma", "TYT"],
    difficulty: "Orta",
  },
  // ===== MATEMATİK =====
  {
    id: "ym1",
    category: "matematik",
    title: "Problemler: Kesir ve Yüzde (TYT Klasiği)",
    summary: "TYT'de her yıl çıkan problem tipi: bir işin/miktarın kesirle veya yüzdeyle ifade edilip kalanının sorulması.",
    detail: "Kesir ve yüzde problemleri TYT Matematik'in en garanti soru grubudur. Temel mantık: bütünü bilinmeyen (genellikle x) alıp verilen kesir/yüzde ilişkilerini adım adım kurmaktır. 'Bir işin önce 1/3'ü, kalanın 1/4'ü yapıldı' türü sorularda her adımda KALAN üzerinden işlem yapılır, baştaki bütün üzerinden değil — en sık yapılan hata budur. Yüzde problemlerinde ardışık değişimler doğrudan toplanmaz: %20 artış sonra %20 azalış, başlangıcın %96'sına (yani %4 azalışa) götürür. Fiyat, maaş, karışım ve nüfus artışı bu konunun tipik bağlamlarıdır.",
    funFact: "'Kalanın' kelimesi altın anahtardır: 'kalanın yarısı' ifadesi gördüğünde, o ana kadar tükettiğini bütünden çıkarıp kalan miktar üzerinden işlem yapmalısın. Bu ayrımı kaçıran öğrenci soruyu yanlış kurar.",
    tags: ["problem", "kesir", "yüzde", "TYT"],
    difficulty: "Orta",
  },
  {
    id: "ym2",
    category: "matematik",
    title: "Fonksiyon Grafiği Okuma (AYT Sık Soru)",
    summary: "AYT'de fonksiyonun grafiğinden değer, kök, artan/azalan aralık ve işaret okuma sık sorulan bir beceridir.",
    detail: "Grafik yorumlama, AYT Matematik'in analiz sorularının temelidir. Grafikten f(a) değerini okumak için x=a'da eğrinin yüksekliğine bakılır. Kökler, grafiğin x eksenini kestiği noktalardır (f(x)=0). Fonksiyonun pozitif olduğu aralıklar grafiğin x ekseninin ÜSTÜNDE, negatif olduğu aralıklar ALTINDA olduğu yerlerdir. Artan aralıkta grafik soldan sağa yükselir (f'>0), azalan aralıkta alçalır (f'<0). Yerel maksimum/minimum, grafiğin tepe/çukur yaptığı noktalardır. Bileşke f(g(a)) sorularında önce içteki g(a) grafikten okunur, sonra o değer dıştaki f'te aranır.",
    funFact: "İki grafiğin kesim noktaları f(x)=g(x) denkleminin çözümüdür. 'Kaç noktada kesişir?' sorusunda cebirsel çözüm yerine grafikleri üst üste düşünmek çok daha hızlıdır.",
    tags: ["fonksiyon", "grafik", "analiz", "AYT"],
    difficulty: "İleri",
  },
  {
    id: "ym3",
    category: "matematik",
    title: "Mutlak Değerli Denklem ve Eşitsizlikler",
    summary: "YKS'de mutlak değerin sıfıra uzaklık olarak yorumlanması ve durum incelemesi sık test edilir.",
    detail: "Mutlak değer |x|, bir sayının sayı doğrusunda sıfıra olan uzaklığıdır; daima negatif değildir. |x| = a (a≥0) denklemi x = a veya x = −a şeklinde iki çözüm verir. |x| < a eşitsizliği −a < x < a aralığını, |x| > a eşitsizliği ise x < −a veya x > a durumunu belirtir. İçinde birden çok mutlak değer bulunan ifadelerde 'kritik noktalar' (içi sıfır yapan değerler) bulunup sayı doğrusu aralıklara ayrılır ve her aralıkta işaret incelemesi yapılır. Üçgen eşitsizliği |a+b| ≤ |a| + |b| de sık kullanılır.",
    funFact: "Sık hata: |x| = −3 denkleminin çözümü YOKTUR çünkü mutlak değer negatif olamaz. Ama |x| + 3 = 0 gibi gizlenmiş biçimlerde bu tuzağı fark etmek gerekir.",
    tags: ["mutlak değer", "denklem", "eşitsizlik", "AYT"],
    difficulty: "İleri",
  },
  // ===== GEOMETRİ =====
  {
    id: "yg1",
    category: "geometri",
    title: "Üçgende Benzerlik (Temel Orantı - Thales)",
    summary: "YKS'de bir üçgende paralel çizilen doğrunun kenarları orantılı böldüğü (Thales) sorusu klasiktir.",
    detail: "Geometrinin en çok soru gelen konularından biri benzerliktir. Bir üçgende, bir kenara paralel çizilen doğru diğer iki kenarı aynı oranda böler (Temel Orantı Teoremi / Thales). Bu, küçük üçgen ile büyük üçgenin benzer (AA) olmasından kaynaklanır. Benzerlikte karşılıklı açılar eşit, kenarlar orantılıdır; benzerlik oranı k ise ÇEVRE oranı k, ALAN oranı k²'dir. 'Kelebek' (X) ve 'temel orantı' şekilleri bu tip soruların çizim kalıplarıdır. Açıortay, kenarortay ve paralel kenar çizimleriyle oluşan orantılar da sık sorulur.",
    funFact: "En kritik hatırlatma: benzer üçgenlerde ALAN oranı kenar oranının KARESİDİR. Kenar oranı 2 ise alan oranı 4'tür. Soru 'alan oranı' isterse kenar oranını karesine yükseltmeyi unutma.",
    tags: ["üçgen", "benzerlik", "thales", "TYT"],
    difficulty: "İleri",
  },
  {
    id: "yg2",
    category: "geometri",
    title: "Çemberde Açı-Yay İlişkileri (Çıkmış Soru)",
    summary: "Merkez açı, çevre açı, teğet-kiriş açı ve Thales'in dik açısı YKS'de tek soruda birlikte sorulur.",
    detail: "Çember, YKS geometrisinin yoğun konusudur ve genelde birden çok açı kuralı tek soruda birleştirilir. Merkez açı, gördüğü yayın tamamına eşittir. Çevre açı, aynı yayın YARISI kadardır; bu yüzden aynı yayı gören tüm çevre açılar eşittir. Çapı gören çevre açı 90°'dir (Thales) — bir kenarın çap olduğunu fark etmek soruyu anında kilitler. Teğet-kiriş açısı gördüğü yayın yarısıdır. Kirişler dörtgeninde karşılıklı açılar toplamı 180°'dir. İç açı (iki kirişin kesişimi) ve dış açı (iki kesenin kesişimi) formülleri de sık gelir.",
    funFact: "Bir çemberde çapı gördüğün anı 90° olarak işaretle: bu bilgi çoğu çember + dik üçgen (Pisagor) karma sorusunun çözüm anahtarıdır.",
    tags: ["çember", "açı", "thales", "AYT"],
    difficulty: "İleri",
  },
  // ===== FİZİK =====
  {
    id: "yf1",
    category: "fizik",
    title: "Hareket Grafikleri (Konum-Hız-İvme)",
    summary: "TYT/AYT Fizik'te grafik yorumlama garanti sorudur: eğim ve alanın ne anlama geldiğini bilmek şarttır.",
    detail: "Hareket grafikleri her yıl sorulur ve iki altın kural çözümü sağlar: (1) Bir grafiğin EĞİMİ türev anlamındadır, (2) grafiğin altındaki ALAN toplam anlamındadır. Konum-zaman grafiğinde eğim HIZ'ı verir; yatay çizgi durgunluğu, eğimin işareti hareket yönünü gösterir. Hız-zaman grafiğinde eğim İVME'yi, altındaki alan ise alınan YOL'u verir. İvme-zaman grafiğinde alan hız değişimini verir. Sabit hızda konum-zaman grafiği doğru, hız-zaman grafiği yataydır; sabit ivmede hız-zaman grafiği eğimli doğrudur.",
    funFact: "En sık karıştırılan nokta: konum-zaman grafiğinde eğim hızı, hız-zaman grafiğinde eğim ivmeyi verir. 'Alan' ise sadece hız-zaman (yol) ve ivme-zaman (hız değişimi) grafiklerinde anlamlıdır — konum-zamanda alanın fiziksel anlamı yoktur.",
    tags: ["hareket", "grafik", "hız", "ivme", "TYT"],
    difficulty: "İleri",
  },
  {
    id: "yf2",
    category: "fizik",
    title: "Kaldırma Kuvveti ve Yüzme Koşulları (Arşimet)",
    summary: "YKS'de bir cismin yüzme/batma/askıda kalma durumu ve batan hacim sık sorulur.",
    detail: "Arşimet ilkesi YKS'nin klasik sorularındandır: bir sıvıya batan cisme, taşırdığı sıvının ağırlığı kadar yukarı yönlü kaldırma kuvveti etki eder (F = V_batan · d_sıvı · g). Cismin durumu yoğunluk karşılaştırmasıyla belirlenir: cisim yoğunluğu < sıvı yoğunluğu ise YÜZER (bir kısmı dışarıda), eşitse ASKIDA kalır (tamamı içeride, her derinlikte durur), büyükse BATAR. Yüzen cisimde 'batan hacim oranı = cisim yoğunluğu / sıvı yoğunluğu'dur. Cisim yüzerken kaldırma kuvveti cismin ağırlığına eşittir. Bir cisim farklı sıvılarda farklı oranda batar; yoğun sıvıda daha az batar.",
    funFact: "Buzdağının su üstünde görünen kısmı sadece ~%10'dur çünkü buz ve deniz suyunun yoğunlukları çok yakındır. 'Batan hacim oranı = yoğunlukların oranı' formülü bu ünlü örneği doğrudan açıklar.",
    tags: ["kaldırma kuvveti", "arşimet", "yoğunluk", "TYT"],
    difficulty: "Orta",
  },
  // ===== KİMYA =====
  {
    id: "yk1",
    category: "kimya",
    title: "Mol Hesaplamaları ve Stokiyometri",
    summary: "YKS Kimya'nın belkemiği: mol-kütle-hacim-tanecik dönüşümleri ve tepkime katsayılarıyla hesap.",
    detail: "Mol kavramı ve stokiyometri, YKS Kimya'da her yıl birden çok soruyla temsil edilir. Dört büyük dönüşüm ezberlenmelidir: mol = kütle/mol kütlesi (n=m/M); tanecik sayısı = mol × 6,022×10²³ (Avogadro); gaz hacmi (NK) = mol × 22,4 L. Tepkimelerde katsayılar mol oranını verir; 'sınırlayıcı bileşen' (önce tükenen madde) ürün miktarını belirler. Verim (%) = (gerçek ürün / teorik ürün) × 100. Soruların çoğu 'verilen bir maddeden ne kadar ürün oluşur?' kalıbındadır ve çözüm daima mol üzerinden yürür.",
    funFact: "Soru 'NK' (normal koşullar) diyorsa 22,4 L/mol dönüşümü neredeyse kesin gerekir. Ayrıca iki reaktif verildiyse mutlaka sınırlayıcı bileşeni bul — fazla olan madde ürünü belirlemez, önce biten belirler.",
    tags: ["mol", "stokiyometri", "avogadro", "TYT"],
    difficulty: "İleri",
  },
  {
    id: "yk2",
    category: "kimya",
    title: "Periyodik Sistemde Özellik Değişimi (Çıkmış Soru)",
    summary: "YKS'de atom yarıçapı, iyonlaşma enerjisi ve elektronegatifliğin cetveldeki değişimi tek soruda karşılaştırılır.",
    detail: "Periyodik özellikler her yıl sorulur ve yön hafızası çözümü sağlar. Soldan sağa: atom yarıçapı AZALIR (çekirdek yükü artar, elektronları daha güçlü çeker); iyonlaşma enerjisi ve elektronegatiflik ARTAR. Yukarıdan aşağıya: atom yarıçapı ARTAR (yeni katman eklenir); iyonlaşma enerjisi ve elektronegatiflik AZALIR. En küçük yarıçap ve en yüksek elektronegatiflik sağ üstte (flor); metalik özellik sol-alta doğru artar. Aynı periyotta metaller solda, ametaller sağda; soy gazlar en sağda ve kararlıdır. İyon yarıçapı: katyon atomundan küçük, anyon atomundan büyüktür.",
    funFact: "İyonlaşma enerjisinde 2A→3A ve 5A→6A geçişlerinde beklenmedik DÜŞÜŞ olur; bunun nedeni 2A ve 5A gruplarının kararlı (dolu/yarı dolu) orbital yapısıdır. Bu 'anormallik' çıkmış sorularda tuzak olarak kullanılır.",
    tags: ["periyodik sistem", "iyonlaşma", "elektronegatiflik", "AYT"],
    difficulty: "İleri",
  },
  // ===== BİYOLOJİ =====
  {
    id: "yb1",
    category: "biyoloji",
    title: "Kalıtım Problemleri (Çaprazlama - Kan Grupları)",
    summary: "YKS Biyoloji'nin en verimli konusu: monohibrit/dihibrit çaprazlama, kan grubu ve eşeye bağlı kalıtım.",
    detail: "Kalıtım problemleri her yıl birden çok soruyla gelir ve Punnett karesiyle güvenle çözülür. Monohibrit Aa × Aa → 3:1 fenotip; dihibrit AaBb × AaBb → 9:3:3:1 oranını verir. Kan grubunda A ve B alelleri eş baskın, 0 çekiniktir; AB grubu eş baskınlığın klasik örneğidir. Eşeye (X'e) bağlı çekinik hastalıklar (renk körlüğü, hemofili) erkeklerde daha sık görülür çünkü erkekte tek X vardır. Soy ağacı sorularında baskın/çekinik ve otozomal/eşeysel ayrımı, etkilenen bireylerin cinsiyet dağılımına bakılarak yapılır.",
    funFact: "Soy ağacında anne-baba etkilenmemişken çocuk etkilenmişse özellik ÇEKİNİKTİR ('ortaya çıktı' demek gizli aleller birleşti demektir). Etkilenenlerin çoğu erkekse büyük olasılıkla X'e bağlı çekiniktir.",
    tags: ["kalıtım", "çaprazlama", "kan grubu", "AYT"],
    difficulty: "İleri",
  },
  {
    id: "yb2",
    category: "biyoloji",
    title: "Enzimler ve Etki Eden Faktörler (Grafik Sorusu)",
    summary: "YKS'de enzim hızının sıcaklık, pH ve substrat derişimiyle değişimini gösteren grafik sorusu klasiktir.",
    detail: "Enzimler biyolojik katalizördür; aktivasyon enerjisini düşürerek tepkimeyi hızlandırır ama kendileri tükenmez. YKS'de en sık enzim hızını etkileyen faktörlerin grafiği sorulur. Sıcaklık arttıkça hız optimum noktaya kadar artar, sonra enzim yapısı bozulunca (denatürasyon) hız hızla düşer. Her enzimin bir optimum pH'ı vardır; bu değerden uzaklaştıkça hız azalır (pepsin asidik, tripsin bazik ortamı sever). Substrat derişimi arttıkça hız önce artar, tüm enzimler doyunca sabitlenir (plato). Enzim miktarı artırılırsa plato daha yükseğe taşınır. Enzimler substrata özgüdür (anahtar-kilit).",
    funFact: "Sıcaklık ile substrat derişimi grafiklerini karıştırma: sıcaklık grafiği optimumdan sonra DÜŞER (denatürasyon), substrat derişimi grafiği ise düşmez, DÜZLEŞİR (plato) — çünkü enzimler doymuştur, bozulmamıştır.",
    tags: ["enzim", "grafik", "metabolizma", "AYT"],
    difficulty: "İleri",
  },
  // ===== TARİH =====
  {
    id: "yh1",
    category: "tarih",
    title: "Kurtuluş Savaşı Kronolojisi (Genelge-Kongre-Antlaşma)",
    summary: "YKS İnkılap'ta olayların sırası ve 'ilk' olma özellikleri (ilk siyasi başarı, ilk kez ulusal egemenlik) sık sorulur.",
    detail: "Kurtuluş Savaşı kronolojisi TYT/AYT İnkılap'ın en verimli konusudur. Sıra: Mondros Ateşkesi (1918, işgaller başlar) → Amasya Genelgesi (milletin bağımsızlığını yine milletin sağlayacağı ilk kez duyurulur) → Erzurum ve Sivas Kongreleri (millî birlik) → TBMM'nin açılışı (23 Nisan 1920, ulusal egemenlik) → Doğu Cephesi/Gümrü (ilk siyasi/askerî başarı) → I. ve II. İnönü, Sakarya (dönüm noktası, savunmadan taarruza), Büyük Taarruz → Mudanya Ateşkesi → Lozan Antlaşması (bağımsızlığın tescili). 'İlk', 'dönüm noktası', 'ulusal egemenlik' vurguları soru köklerinde sık geçer.",
    funFact: "Sakarya Meydan Muharebesi 'dönüm noktası'dır: 1683 Viyana'dan beri süren geri çekilme sona erdi, savunmadan taarruza geçildi. Bu zaferden sonra Mustafa Kemal'e 'Gazi' unvanı ve mareşallik verildi.",
    tags: ["kurtuluş savaşı", "inkılap", "kronoloji", "TYT"],
    difficulty: "Orta",
  },
  {
    id: "yh2",
    category: "tarih",
    title: "Osmanlı Devleti'nde Kültür ve Yönetim Yapısı",
    summary: "YKS'de Osmanlı'da tımar sistemi, divan, millet sistemi ve merkez-taşra yönetimi karşılaştırmalı sorulur.",
    detail: "Osmanlı yönetim ve kültür yapısı AYT Tarih'te sık sorulur. Merkezde padişah ve Divan-ı Hümayun (devlet işlerinin görüşüldüğü kurul) vardır; sadrazam padişahın mutlak vekilidir. Taşrada tımar sistemi uygulanır: devlet toprağın (miri arazi) gelirini hizmet karşılığı verir, tımarlı sipahiler asker yetiştirir — hem üretim hem ordu hem güvenlik sağlanır. Millet sistemi, gayrimüslimlerin dinî-hukukî özerkliğini tanır. Ekonomide 'gedik' (esnaf), 'lonca' (meslek örgütü) ve narh (fiyat denetimi) öne çıkar. Bu kurumların bozulması Duraklama ve Gerileme'nin iç nedenleri olarak sorulur.",
    funFact: "Tımar sisteminin bozulması hem tarımsal üretimi hem ordu düzenini (tımarlı sipahi sayısı) aynı anda etkilediği için Osmanlı'nın gerilemesinde zincirleme bir çöküş yaratmıştır; çıkmış sorularda 'neden-sonuç' ilişkisiyle sorulur.",
    tags: ["osmanlı", "tımar", "divan", "AYT"],
    difficulty: "Orta",
  },
  // ===== COĞRAFYA =====
  {
    id: "yc1",
    category: "cografya",
    title: "Türkiye'de Sıcaklık ve Yükselti (Grafik/Harita Yorumu)",
    summary: "YKS Coğrafya'da enlem, yükselti, denize uzaklık ve bakının sıcaklığa etkisi harita üzerinden sorulur.",
    detail: "Türkiye'nin sıcaklık dağılışı YKS'de harita ve grafik yorumuyla sık sorulur. Belirleyici faktörler: enlem (güneye gidince sıcaklık artar), yükselti (her 100 m'de ~0,5°C azalır — Türkiye dağlık olduğu için iç kesimler serindir), denize uzaklık (kıyılar ılıman, iç bölgeler karasal), bakı (güneşe dönük güney yamaçlar daha sıcak) ve okyanus/deniz etkisidir. Kıyı bölgelerde yıllık sıcaklık farkı azdır; iç bölgelerde (karasal) yaz-kış farkı fazladır. Aynı enlemde iki yer arasında sıcaklık farkı varsa neden çoğunlukla yükselti veya denize uzaklıktır.",
    funFact: "Türkiye'de en düşük sıcaklıklar genelde Doğu Anadolu'da görülür; bunun nedeni sadece kuzeyde olması değil, YÜKSELTİsinin çok fazla olmasıdır. Enlem etkisini yükselti bastırır — bu, çıkmış sorularda klasik bir ayrımdır.",
    tags: ["türkiye", "sıcaklık", "yükselti", "iklim", "TYT"],
    difficulty: "Orta",
  },
  {
    id: "yc2",
    category: "cografya",
    title: "Nüfus Piramitleri ve Nüfus Politikaları",
    summary: "YKS'de bir ülkenin gelişmişlik düzeyini nüfus piramidinden okuma ve nüfus politikası yorumu sık çıkar.",
    detail: "Nüfus piramitleri YKS Coğrafya'nın grafik yorumlama sorularındandır. Geniş tabanlı (üçgen) piramit: yüksek doğum oranı, genç ve hızla artan nüfus → az gelişmiş ülke. Dar tabanlı (arı kovanı/urn) piramit: düşük doğum oranı, yaşlanan nüfus → gelişmiş ülke. Tabanın daralması doğum oranının düştüğünü, tepenin genişlemesi ortalama yaşam süresinin arttığını gösterir. Az gelişmiş ülkeler nüfus artışını YAVAŞLATICI (aile planlaması), gelişmiş/yaşlanan ülkeler ARTIRICI (doğum teşviki) politikalar uygular. Türkiye, piramidi giderek daralan bir geçiş ülkesidir.",
    funFact: "Piramidin tabanındaki ani daralma çoğunlukla bir savaş, salgın ya da ekonomik kriz nedeniyle doğumların düştüğü dönemi gösterir; grafik yorum sorularında bu 'çentik' üzerinden tarihsel olay çıkarımı istenebilir.",
    tags: ["nüfus", "piramit", "nüfus politikası", "TYT"],
    difficulty: "Orta",
  },
  // ===== EDEBİYAT =====
  {
    id: "ye1",
    category: "edebiyat",
    title: "Şiirde Söz Sanatlarını Ayırt Etme (AYT Klasiği)",
    summary: "AYT Edebiyat'ta bir dizedeki söz sanatını (teşbih, istiare, teşhis, kinaye, mecaz-ı mürsel) belirleme sık sorulur.",
    detail: "Söz sanatları AYT Edebiyat'ın değişmez sorusudur ve ayrımları bilmek şarttır. Teşbih (benzetme): dört ögesiyle benzetme (benzeyen, benzetilen, yön, edat). İstiare: benzetmenin tek ögesiyle yapılır — açık istiare (sadece benzetilen: 'gökte aslan uçuyor' = kartal), kapalı istiare (sadece benzeyen). Teşhis (kişileştirme): insan dışı varlığa insan özelliği verme; her teşhiste kapalı istiare de vardır. İntak: konuşturma (her intak teşhistir). Kinaye: hem gerçek hem mecaz anlama gelebilecek söz (asıl mecaz kastedilir). Mecaz-ı mürsel (ad aktarması): benzetme amacı olmadan bir sözü başka anlamda kullanma ('Sobayı yaktım' = odunu/kömürü).",
    funFact: "Kinaye ile mecaz-ı mürseli ayırt etmenin yolu: kinayede söz gerçek anlamıyla da düşünülebilir ama asıl mecaz kastedilir ('Onun eli açıktır' — hem gerçek hem cömert). Mecaz-ı mürselde ise gerçek anlam kastedilmez ('Ankara açıklama yaptı' = hükümet).",
    tags: ["söz sanatları", "istiare", "kinaye", "AYT"],
    difficulty: "İleri",
  },
  {
    id: "ye2",
    category: "edebiyat",
    title: "Edebî Dönemleri ve Sanatçıları Eşleştirme",
    summary: "YKS'de bir sanatçının hangi döneme/akıma ait olduğu ve eserleriyle eşleştirilmesi sık sorulur.",
    detail: "AYT Edebiyat'ta dönem-sanatçı-eser eşleştirmesi yüksek verimli bir konudur. Tanzimat (toplum için sanat, Batılı türlerin girişi): Şinasi, Namık Kemal, Ziya Paşa. Servet-i Fünun (sanat için sanat, ağır dil): Halit Ziya (Aşk-ı Memnu), Tevfik Fikret, Cenap Şahabettin. Millî Edebiyat (sade dil, hece ölçüsü): Ömer Seyfettin, Ziya Gökalp, Mehmet Emin Yurdakul. Cumhuriyet: Garip (Orhan Veli), İkinci Yeni, bağımsızlar (Yahya Kemal, Necip Fazıl). 'İlk'ler sık sorulur: ilk yerli roman Taaşşuk-ı Talat ve Fitnat, ilk çeviri roman Telemak, ilk realist roman Araba Sevdası.",
    funFact: "Karıştırma tuzağı: Ahmet Haşim hem Fecr-i Âti'de yer aldı hem bağımsız sayılır; Yakup Kadri ise Fecr-i Âti'den başlayıp Millî Edebiyat'a ve Cumhuriyet romanına geçti. Sanatçının 'birden çok dönemde' bulunabileceğini unutma.",
    tags: ["edebi dönem", "sanatçı", "eser", "AYT"],
    difficulty: "İleri",
  },
];
