import type { Question } from "./data";

// extraCapsules3 (yeni konular) için sorular — her konu 4 soru
export const questionsExtra7: Question[] = [
  // tr31 Tamlamalar
  { id: "q_tr31_1", capsuleId: "tr31", category: "turkce", question: "'Kapının kolu' söz öbeği hangi tamlamadır?", options: ["Belirtisiz isim tamlaması", "Belirtili isim tamlaması", "Sıfat tamlaması", "Takısız tamlama"], correctIndex: 1, explanation: "Her iki öge de ek aldığından belirtili isim tamlamasıdır." },
  { id: "q_tr31_2", capsuleId: "tr31", category: "turkce", question: "'Güzel ev' söz öbeği hangi tür tamlamadır?", options: ["İsim tamlaması", "Sıfat tamlaması", "Belirtili tamlama", "Zincirleme tamlama"], correctIndex: 1, explanation: "Sıfat + isimden oluştuğu için sıfat tamlamasıdır." },
  { id: "q_tr31_3", capsuleId: "tr31", category: "turkce", question: "'Kapı kolu' örneğinde hangi tamlama vardır?", options: ["Belirtili isim tamlaması", "Belirtisiz isim tamlaması", "Sıfat tamlaması", "Edat öbeği"], correctIndex: 1, explanation: "Yalnız tamlanan ek aldığından belirtisiz isim tamlamasıdır." },
  { id: "q_tr31_4", capsuleId: "tr31", category: "turkce", question: "'Altın yüzük' söz öbeği aslında hangi tamlamadır?", options: ["Takısız isim tamlaması", "Sıfat tamlaması", "Belirtili tamlama", "Zincirleme"], correctIndex: 1, explanation: "Takısız isim tamlaması yoktur; bu yapı bir sıfat tamlamasıdır." },
  // tr32 Ünsüz benzeşmesi
  { id: "q_tr32_1", capsuleId: "tr32", category: "turkce", question: "'sokak' sözcüğüne '-da' eki gelince doğru yazım hangisidir?", options: ["sokakda", "sokakta", "sokağda", "sokağta"], correctIndex: 1, explanation: "Sert ünsüzden sonra ek sertleşir: sokak+da → sokakta." },
  { id: "q_tr32_2", capsuleId: "tr32", category: "turkce", question: "'kitap' sözcüğüne '-cı' eki gelince ne olur?", options: ["kitapcı", "kitapçı", "kitabçı", "kitabcı"], correctIndex: 1, explanation: "Ünsüz benzeşmesiyle 'c' sertleşerek 'ç' olur: kitapçı." },
  { id: "q_tr32_3", capsuleId: "tr32", category: "turkce", question: "Ünsüz benzeşmesi (sertleşme) nasıl gerçekleşir?", options: ["Yumuşak ünsüz, sert ünsüze uyar", "Sert ünsüz yumuşar", "Ünlü düşer", "Ünlü türer"], correctIndex: 0, explanation: "Sert ünsüzden sonra gelen ekin yumuşak ünsüzü sertleşir." },
  { id: "q_tr32_4", capsuleId: "tr32", category: "turkce", question: "Aşağıdakilerden hangisinde ünsüz benzeşmesi vardır?", options: ["evde", "ağaçta", "arabada", "kalemde"], correctIndex: 1, explanation: "'ağaç+da → ağaçta' örneğinde ek sertleşmiştir (benzeşme)." },
  // mat36 Bölme ve kalan
  { id: "q_mat36_1", capsuleId: "mat36", category: "matematik", question: "17 sayısı 5'e bölündüğünde kalan kaçtır?", options: ["1", "2", "3", "4"], correctIndex: 1, explanation: "17 = 5·3 + 2 olduğundan kalan 2'dir." },
  { id: "q_mat36_2", capsuleId: "mat36", category: "matematik", question: "Kalanlı bölmede kalan için ne söylenir?", options: ["Bölenden büyüktür", "Bölenden küçüktür", "Bölene eşittir", "Her zaman 0'dır"], correctIndex: 1, explanation: "Kalan daima bölenden küçük ve negatif olmayan bir tam sayıdır." },
  { id: "q_mat36_3", capsuleId: "mat36", category: "matematik", question: "Bir sayının 10'a bölümünden kalan neye eşittir?", options: ["Onlar basamağına", "Birler basamağına", "Rakamları toplamına", "0'a"], correctIndex: 1, explanation: "Bir sayının 10'a bölümünden kalan, birler basamağıdır." },
  { id: "q_mat36_4", capsuleId: "mat36", category: "matematik", question: "23 sayısı 4'e bölündüğünde bölüm ve kalan kaçtır?", options: ["Bölüm 5, kalan 3", "Bölüm 4, kalan 7", "Bölüm 6, kalan 1", "Bölüm 5, kalan 2"], correctIndex: 0, explanation: "23 = 4·5 + 3 olduğundan bölüm 5, kalan 3'tür." },
  // mat37 Parabol
  { id: "q_mat37_1", capsuleId: "mat37", category: "matematik", question: "y=ax²+bx+c parabolünde a>0 ise kollar nasıl açılır?", options: ["Aşağı", "Yukarı", "Sağa", "Sola"], correctIndex: 1, explanation: "a>0 ise parabolün kolları yukarı açılır." },
  { id: "q_mat37_2", capsuleId: "mat37", category: "matematik", question: "Parabolün tepe noktasının apsisi (x) hangi formülle bulunur?", options: ["-b/2a", "b/a", "c/a", "-c/b"], correctIndex: 0, explanation: "Tepe noktasının apsisi x = -b/2a'dır." },
  { id: "q_mat37_3", capsuleId: "mat37", category: "matematik", question: "Parabol y eksenini hangi noktada keser?", options: ["a", "b", "c", "0"], correctIndex: 2, explanation: "x=0 için y=c olur; parabol y eksenini c noktasında keser." },
  { id: "q_mat37_4", capsuleId: "mat37", category: "matematik", question: "a<0 olan bir parabolün tepe noktası nasıldır?", options: ["Minimum", "Maksimum", "Sıfır", "Belirsiz"], correctIndex: 1, explanation: "a<0 ise kollar aşağı açılır ve tepe noktası maksimumdur." },
  // geo21 Koni ve silindir
  { id: "q_geo21_1", capsuleId: "geo21", category: "geometri", question: "Silindirin hacim formülü hangisidir?", options: ["πr²h", "(1/3)πr²h", "4πr²", "2πrh"], correctIndex: 0, explanation: "Silindirin hacmi πr²h'dir." },
  { id: "q_geo21_2", capsuleId: "geo21", category: "geometri", question: "Koninin hacmi, aynı taban ve yükseklikteki silindirin kaçta kaçıdır?", options: ["1/2", "1/3", "2/3", "1/4"], correctIndex: 1, explanation: "Koninin hacmi aynı ölçülerdeki silindirin üçte biridir." },
  { id: "q_geo21_3", capsuleId: "geo21", category: "geometri", question: "Taban yarıçapı 2, yüksekliği 5 olan silindirin hacmi kaç π'dir?", options: ["10π", "20π", "40π", "25π"], correctIndex: 1, explanation: "V=πr²h=π·4·5=20π." },
  { id: "q_geo21_4", capsuleId: "geo21", category: "geometri", question: "Silindirin yanal alan formülü hangisidir?", options: ["πr²", "2πrh", "4πr²", "(1/3)πr²h"], correctIndex: 1, explanation: "Silindirin yanal alanı 2πrh'dir." },
  // geo22 Vektörler
  { id: "q_geo22_1", capsuleId: "geo22", category: "geometri", question: "Vektör nasıl bir büyüklüktür?", options: ["Yalnız büyüklüğü olan", "Yönlü doğru parçası (büyüklük ve yön)", "Yalnız yönü olan", "Sayısal olmayan"], correctIndex: 1, explanation: "Vektör, hem büyüklüğü hem yönü olan yönlü bir doğru parçasıdır." },
  { id: "q_geo22_2", capsuleId: "geo22", category: "geometri", question: "İki vektör hangi yöntemle toplanabilir?", options: ["Bölme", "Uç uca ekleme / paralelkenar", "Kare alma", "Logaritma"], correctIndex: 1, explanation: "Vektörler uç uca ekleme veya paralelkenar yöntemiyle toplanır." },
  { id: "q_geo22_3", capsuleId: "geo22", category: "geometri", question: "Bir vektörün ters yönlüsü nasıldır?", options: ["Farklı büyüklükte", "Aynı büyüklükte zıt yönde", "Sıfır", "Dik"], correctIndex: 1, explanation: "Ters vektör aynı büyüklükte, zıt yönlüdür." },
  { id: "q_geo22_4", capsuleId: "geo22", category: "geometri", question: "Kapalı bir çokgen boyunca uç uca eklenen vektörlerin bileşkesi kaçtır?", options: ["Çevre kadar", "Sıfır", "Alan kadar", "İki katı"], correctIndex: 1, explanation: "Başlangıç ve bitiş aynı noktada olduğundan bileşke sıfırdır." },
  // fiz23 Atışlar
  { id: "q_fiz23_1", capsuleId: "fiz23", category: "fizik", question: "Yatay atışta yatay hız nasıl davranır?", options: ["Artar", "Sabit kalır", "Azalır", "Sıfırlanır"], correctIndex: 1, explanation: "Yatay atışta yatay hız sabit kalır (yatayda ivme yoktur)." },
  { id: "q_fiz23_2", capsuleId: "fiz23", category: "fizik", question: "Yatay atışta düşey hareket nasıl bir harekettir?", options: ["Sabit hızlı", "Serbest düşme", "Duruş", "Yavaşlama"], correctIndex: 1, explanation: "Yatay atışta düşey hareket serbest düşmedir." },
  { id: "q_fiz23_3", capsuleId: "fiz23", category: "fizik", question: "Aynı yükseklikten biri yatay atılan, biri serbest bırakılan iki cisim ne zaman yere düşer?", options: ["Yatay atılan önce", "Serbest bırakılan önce", "Aynı anda", "Belirsiz"], correctIndex: 2, explanation: "Düşey hareketleri aynı olduğundan ikisi de aynı anda yere düşer." },
  { id: "q_fiz23_4", capsuleId: "fiz23", category: "fizik", question: "Eğik atışta ilk hız nasıl incelenir?", options: ["Tek yönde", "Yatay ve düşey bileşenlere ayrılarak", "Sadece düşey", "İncelenmez"], correctIndex: 1, explanation: "Eğik atışta ilk hız yatay ve düşey bileşenlere ayrılarak incelenir." },
  // fiz24 İndüksiyon
  { id: "q_fiz24_1", capsuleId: "fiz24", category: "fizik", question: "Bir bobinde elektrik akımı nasıl indüklenir?", options: ["Sabit manyetik alanla", "Değişen manyetik alanla", "Sıcaklıkla", "Işıkla"], correctIndex: 1, explanation: "Değişen manyetik alan bobinde akım (indüksiyon) oluşturur." },
  { id: "q_fiz24_2", capsuleId: "fiz24", category: "fizik", question: "Jeneratörler hangi enerji dönüşümünü yapar?", options: ["Elektrik → ısı", "Mekanik → elektrik", "Işık → elektrik", "Kimyasal → ısı"], correctIndex: 1, explanation: "Jeneratörler mekanik enerjiyi elektrik enerjisine çevirir." },
  { id: "q_fiz24_3", capsuleId: "fiz24", category: "fizik", question: "İndüklenen akımın yönünü belirleyen yasa hangisidir?", options: ["Ohm yasası", "Lenz yasası", "Newton yasası", "Pascal ilkesi"], correctIndex: 1, explanation: "İndüklenen akımın yönünü Lenz yasası belirler." },
  { id: "q_fiz24_4", capsuleId: "fiz24", category: "fizik", question: "Manyetik akıdaki değişimin elektromotor kuvvet oluşturduğunu açıklayan yasa hangisidir?", options: ["Faraday yasası", "Coulomb yasası", "Charles yasası", "Boyle yasası"], correctIndex: 0, explanation: "Faraday yasası, manyetik akı değişiminin emk oluşturduğunu açıklar." },
  // kim21 Molarite
  { id: "q_kim21_1", capsuleId: "kim21", category: "kimya", question: "Molarite nasıl hesaplanır?", options: ["mol / hacim (L)", "kütle / mol", "hacim / mol", "mol × hacim"], correctIndex: 0, explanation: "Molarite (M) = çözünen mol sayısı / çözelti hacmi (litre)." },
  { id: "q_kim21_2", capsuleId: "kim21", category: "kimya", question: "2 litre suda 4 mol tuz çözülürse molarite kaçtır?", options: ["0,5 M", "2 M", "4 M", "8 M"], correctIndex: 1, explanation: "M = 4 mol / 2 L = 2 M." },
  { id: "q_kim21_3", capsuleId: "kim21", category: "kimya", question: "Bir çözelti su eklenerek seyreltilince ne değişmez?", options: ["Derişim", "Hacim", "Çözünen mol sayısı", "Molarite"], correctIndex: 2, explanation: "Seyreltmede çözünen mol sayısı sabit kalır (M₁V₁=M₂V₂)." },
  { id: "q_kim21_4", capsuleId: "kim21", category: "kimya", question: "Derişik çözelti için ne söylenir?", options: ["Çözünen az", "Çözünen fazla", "Su fazla", "Çözünen yok"], correctIndex: 1, explanation: "Derişik çözeltide çözünen madde miktarı fazladır." },
  // kim22 Redoks
  { id: "q_kim22_1", capsuleId: "kim22", category: "kimya", question: "Redoks tepkimesinde elektron veren madde ne olur?", options: ["İndirgenir", "Yükseltgenir", "Değişmez", "Çökelir"], correctIndex: 1, explanation: "Elektron veren madde yükseltgenir." },
  { id: "q_kim22_2", capsuleId: "kim22", category: "kimya", question: "Elektron alan madde için ne söylenir?", options: ["Yükseltgenir", "İndirgenir", "Yanar", "Buharlaşır"], correctIndex: 1, explanation: "Elektron alan madde indirgenir." },
  { id: "q_kim22_3", capsuleId: "kim22", category: "kimya", question: "Aşağıdakilerden hangisi bir redoks olayıdır?", options: ["Şekerin çözünmesi", "Demirin paslanması", "Buzun erimesi", "Suyun kaynaması"], correctIndex: 1, explanation: "Paslanma bir yükseltgenme-indirgenme (redoks) olayıdır." },
  { id: "q_kim22_4", capsuleId: "kim22", category: "kimya", question: "Pillerde hangi dönüşüm gerçekleşir?", options: ["Elektrik → kimyasal", "Kimyasal → elektrik (redoks)", "Isı → ışık", "Işık → elektrik"], correctIndex: 1, explanation: "Pillerde kimyasal enerji redoks tepkimeleriyle elektrik enerjisine dönüşür." },
  // biyo21 Hormonlar
  { id: "q_biyo21_1", capsuleId: "biyo21", category: "biyoloji", question: "Kan şekerini düşüren hormon hangisidir?", options: ["Adrenalin", "İnsulin", "Tiroksin", "Testosteron"], correctIndex: 1, explanation: "İnsülin kan şekerini düşüren hormondur." },
  { id: "q_biyo21_2", capsuleId: "biyo21", category: "biyoloji", question: "'Ana bez' olarak adlandırılan ve diğer bezleri yöneten bez hangisidir?", options: ["Tiroit", "Hipofiz", "Böbrek üstü", "Pankreas"], correctIndex: 1, explanation: "Hipofiz, diğer iç salgı bezlerini yöneten 'ana bez'dir." },
  { id: "q_biyo21_3", capsuleId: "biyo21", category: "biyoloji", question: "İnsülin eksikliği hangi hastalığa yol açar?", options: ["Guatr", "Diyabet (şeker)", "Anemi", "Raşitizm"], correctIndex: 1, explanation: "İnsülin eksikliği veya yetersiz kullanımı diyabete yol açar." },
  { id: "q_biyo21_4", capsuleId: "biyo21", category: "biyoloji", question: "Hormonların sinir sistemine göre etkisi nasıldır?", options: ["Daha hızlı ve kısa", "Daha yavaş ve uzun süreli", "Aynı hızda", "Etkisiz"], correctIndex: 1, explanation: "Hormonlar daha yavaş ama uzun süreli etki eder." },
  // biyo22 Ekoloji
  { id: "q_biyo22_1", capsuleId: "biyo22", category: "biyoloji", question: "Popülasyon nedir?", options: ["Farklı türlerin toplamı", "Aynı türden bireyler topluluğu", "Cansız çevre", "Tek bir birey"], correctIndex: 1, explanation: "Popülasyon, belirli alanda yaşayan aynı türden bireyler topluluğudur." },
  { id: "q_biyo22_2", capsuleId: "biyo22", category: "biyoloji", question: "Popülasyon büyüklüğünü etkileyen faktörlerden biri değildir?", options: ["Doğum", "Ölüm", "Göç", "Toprak rengi"], correctIndex: 3, explanation: "Popülasyon; doğum, ölüm ve göçlerle değişir." },
  { id: "q_biyo22_3", capsuleId: "biyo22", category: "biyoloji", question: "Farklı popülasyonların bir arada yaşamasına ne denir?", options: ["Komünite", "Birey", "Tür", "Organ"], correctIndex: 0, explanation: "Farklı popülasyonların bir arada yaşamasına komünite denir." },
  { id: "q_biyo22_4", capsuleId: "biyo22", category: "biyoloji", question: "Bir ortamın besleyebileceği en fazla birey sayısına ne denir?", options: ["Popülasyon yoğunluğu", "Taşıma kapasitesi", "Doğum oranı", "Göç"], correctIndex: 1, explanation: "Ortamın besleyebileceği en fazla birey sayısı taşıma kapasitesidir." },
  // tar21 Anadolu uygarlıkları
  { id: "q_tar21_1", capsuleId: "tar21", category: "tarih", question: "Tarihte parayı (madeni sikke) ilk kullanan uygarlık hangisidir?", options: ["Frigler", "Lidyalılar", "Urartular", "Hititler"], correctIndex: 1, explanation: "Parayı ilk kullanan uygarlık Lidyalılardır." },
  { id: "q_tar21_2", capsuleId: "tar21", category: "tarih", question: "Su kanalları ve kaleleriyle ünlü Anadolu uygarlığı hangisidir?", options: ["İyonlar", "Urartular", "Frigler", "Lidyalılar"], correctIndex: 1, explanation: "Urartular su kanalları ve kaleleriyle ünlüdür." },
  { id: "q_tar21_3", capsuleId: "tar21", category: "tarih", question: "Bilim ve felsefede ilerleyen (Thales, Pisagor) Anadolu uygarlığı hangisidir?", options: ["İyonlar", "Hititler", "Frigler", "Urartular"], correctIndex: 0, explanation: "İyonlar bilim ve felsefede ilerlemiştir (Thales, Pisagor)." },
  { id: "q_tar21_4", capsuleId: "tar21", category: "tarih", question: "Kral Midas efsanesi hangi uygarlığa aittir?", options: ["Lidyalılar", "Frigler", "Urartular", "İyonlar"], correctIndex: 1, explanation: "Kral Midas efsanesi tarımla uğraşan Friglere aittir." },
  // tar22 Çağdaş Türkiye
  { id: "q_tar22_1", capsuleId: "tar22", category: "tarih", question: "Türkiye'de çok partili siyasi hayata geçiş hangi yıl olmuştur?", options: ["1923", "1938", "1946", "1960"], correctIndex: 2, explanation: "Çok partili hayata 1946'da geçilmiştir." },
  { id: "q_tar22_2", capsuleId: "tar22", category: "tarih", question: "Kıbrıs Barış Harekâtı hangi yıl gerçekleşmiştir?", options: ["1963", "1971", "1974", "1980"], correctIndex: 2, explanation: "Kıbrıs Barış Harekâtı 1974'te gerçekleşmiştir." },
  { id: "q_tar22_3", capsuleId: "tar22", category: "tarih", question: "1950'de iktidara gelen parti hangisidir?", options: ["CHP", "Demokrat Parti", "AP", "MSP"], correctIndex: 1, explanation: "1950 seçimlerinde Demokrat Parti iktidara gelmiştir." },
  { id: "q_tar22_4", capsuleId: "tar22", category: "tarih", question: "Türkiye NATO'ya hangi yıl katılmıştır?", options: ["1945", "1952", "1963", "1974"], correctIndex: 1, explanation: "Türkiye 1952'de NATO'ya katılmıştır." },
  // cog21 Ulaşım ve turizm
  { id: "q_cog21_1", capsuleId: "cog21", category: "cografya", question: "Türkiye'de en yaygın ulaşım türü hangisidir?", options: ["Demir yolu", "Kara yolu", "Deniz yolu", "Hava yolu"], correctIndex: 1, explanation: "Türkiye'de en yaygın ulaşım türü kara yoludur." },
  { id: "q_cog21_2", capsuleId: "cog21", category: "cografya", question: "Deniz ulaşımında stratejik önem taşıyan yerler hangileridir?", options: ["Ovalar", "Boğazlar", "Dağlar", "Göller"], correctIndex: 1, explanation: "İstanbul ve Çanakkale Boğazları deniz ulaşımında stratejiktir." },
  { id: "q_cog21_3", capsuleId: "cog21", category: "cografya", question: "Turizmin ülke ekonomisine temel katkısı nedir?", options: ["Döviz girdisi sağlaması", "Nüfusu azaltması", "İklimi değiştirmesi", "Toprağı zenginleştirmesi"], correctIndex: 0, explanation: "Turizm önemli bir döviz girdisi kaynağıdır." },
  { id: "q_cog21_4", capsuleId: "cog21", category: "cografya", question: "Türkiye'nin turizmde öne çıkmasını sağlayan zenginliklerden biri değildir?", options: ["Tarihi eserler", "Doğal güzellikler", "Kültürel miras", "Çöl iklimi"], correctIndex: 3, explanation: "Türkiye tarihi, doğal ve kültürel zenginlikleriyle turizmde öne çıkar." },
  // cog22 Madenler
  { id: "q_cog22_1", capsuleId: "cog22", category: "cografya", question: "Türkiye hangi madende dünya rezervlerinde ilk sıralardadır?", options: ["Altın", "Bor", "Petrol", "Elmas"], correctIndex: 1, explanation: "Türkiye bor rezervlerinde dünyada ilk sıralarda yer alır." },
  { id: "q_cog22_2", capsuleId: "cog22", category: "cografya", question: "Termik santrallerde kullanılan yer altı kaynağı hangisidir?", options: ["Mermer", "Linyit", "Bor", "Krom"], correctIndex: 1, explanation: "Linyit (kömür) termik santrallerde enerji üretiminde kullanılır." },
  { id: "q_cog22_3", capsuleId: "cog22", category: "cografya", question: "Madenlerin sanayideki temel rolü nedir?", options: ["Hammadde olmaları", "Enerji tüketmeleri", "Nüfus artırmaları", "İklim oluşturmaları"], correctIndex: 0, explanation: "Madenler sanayinin hammaddesini oluşturur." },
  { id: "q_cog22_4", capsuleId: "cog22", category: "cografya", question: "Yenilenemeyen doğal kaynaklar için ne yapılmalıdır?", options: ["Sınırsız kullanılmalı", "Bilinçli kullanılmalı", "Hiç kullanılmamalı", "İthal edilmeli"], correctIndex: 1, explanation: "Yenilenemeyen kaynaklar tükenebilir olduğundan bilinçli kullanılmalıdır." },
  // ede21 Halk hikâyeleri
  { id: "q_ede21_1", capsuleId: "ede21", category: "edebiyat", question: "Aşağıdakilerden hangisi bir aşk hikâyesidir?", options: ["Köroğlu", "Kerem ile Aslı", "Dede Korkut kahramanlıkları", "Battal Gazi"], correctIndex: 1, explanation: "Kerem ile Aslı bir aşk hikâyesidir; Köroğlu kahramanlık konuludur." },
  { id: "q_ede21_2", capsuleId: "ede21", category: "edebiyat", question: "Köroğlu hikâyesi hangi konuyu işler?", options: ["Aşk", "Kahramanlık", "Din", "Doğa"], correctIndex: 1, explanation: "Köroğlu bir kahramanlık hikâyesidir." },
  { id: "q_ede21_3", capsuleId: "ede21", category: "edebiyat", question: "Halk hikâyeleri genellikle nasıl anlatılır?", options: ["Yazılı olarak dağıtılır", "Âşıklar tarafından saz eşliğinde", "Tiyatroda sahnelenerek", "Gazetede yayımlanarak"], correctIndex: 1, explanation: "Halk hikâyeleri âşıklar tarafından saz eşliğinde anlatılır." },
  { id: "q_ede21_4", capsuleId: "ede21", category: "edebiyat", question: "Halk hikâyeleri edebiyat tarihinde neyin arasında köprü kabul edilir?", options: ["Şiir ve makale", "Destan ve roman", "Tiyatro ve deneme", "Masal ve fıkra"], correctIndex: 1, explanation: "Halk hikâyeleri destan geleneğiyle roman arasında köprü kabul edilir." },
  // ede22 Bağımsız şairler
  { id: "q_ede22_1", capsuleId: "ede22", category: "edebiyat", question: "'İstanbul şairi' olarak anılan ve aruzu ustaca kullanan şair kimdir?", options: ["Necip Fazıl", "Yahya Kemal", "Orhan Veli", "Nazım Hikmet"], correctIndex: 1, explanation: "Yahya Kemal Beyatlı 'İstanbul şairi' olarak anılır." },
  { id: "q_ede22_2", capsuleId: "ede22", category: "edebiyat", question: "Mistik ve metafizik temalar işleyen bağımsız şair kimdir?", options: ["Necip Fazıl Kısakürek", "Tevfik Fikret", "Şinasi", "Fuzûlî"], correctIndex: 0, explanation: "Necip Fazıl Kısakürek mistik ve metafizik temalar işlemiştir." },
  { id: "q_ede22_3", capsuleId: "ede22", category: "edebiyat", question: "Bağımsız şairlerin ortak özelliği nedir?", options: ["Belli bir akıma bağlı kalmamaları", "Yalnız hece ölçüsü kullanmaları", "Roman yazmaları", "Aynı dergide toplanmaları"], correctIndex: 0, explanation: "Bağımsız şairler belli bir topluluğa/akıma bağlı kalmadan özgün eser vermiştir." },
  { id: "q_ede22_4", capsuleId: "ede22", category: "edebiyat", question: "Yahya Kemal hangi iki geleneği birleştirmiştir?", options: ["Divan şiiri ve modern şiir", "Halk ve tiyatro", "Roman ve deneme", "Masal ve fıkra"], correctIndex: 0, explanation: "Yahya Kemal, divan şiiri geleneğini modern şiirle birleştirmiştir." },
  // fel18 Toplum felsefesi
  { id: "q_fel18_1", capsuleId: "fel18", category: "felsefe", question: "Toplum felsefesi neyi inceler?", options: ["Sayıları", "Toplumun yapısı ve düzenini", "Doğa olaylarını", "Yıldızları"], correctIndex: 1, explanation: "Toplum felsefesi, toplumun yapısını, düzenini ve bireyle ilişkisini inceler." },
  { id: "q_fel18_2", capsuleId: "fel18", category: "felsefe", question: "'Mukaddime' adlı eseriyle sosyolojinin öncüsü kabul edilen düşünür kimdir?", options: ["İbn Sina", "İbn Haldun", "Farabi", "Gazali"], correctIndex: 1, explanation: "İbn Haldun, 'Mukaddime' ile sosyolojinin öncüsü kabul edilir." },
  { id: "q_fel18_3", capsuleId: "fel18", category: "felsefe", question: "Toplum felsefesinin temel kavramlarından biri değildir?", options: ["Adalet", "Dayanışma", "Fotosentez", "Toplumsal düzen"], correctIndex: 2, explanation: "Adalet, dayanışma ve düzen toplum felsefesinin kavramlarıdır; fotosentez değildir." },
  { id: "q_fel18_4", capsuleId: "fel18", category: "felsefe", question: "Toplum felsefesinden doğan bilim hangisidir?", options: ["Fizik", "Sosyoloji", "Kimya", "Astronomi"], correctIndex: 1, explanation: "Sosyoloji, toplum felsefesinden doğan bir bilimdir." },
  // fel19 Atomculuk
  { id: "q_fel19_1", capsuleId: "fel19", category: "felsefe", question: "Atomculuğa göre evren neyden oluşur?", options: ["Su ve ateş", "Atom ve boşluk", "Sayılar", "İdealar"], correctIndex: 1, explanation: "Atomculara göre evren, bölünemeyen atomlar ve boşluktan oluşur." },
  { id: "q_fel19_2", capsuleId: "fel19", category: "felsefe", question: "Atomculuğun öncüsü olan filozof kimdir?", options: ["Platon", "Demokritos", "Sokrates", "Aristoteles"], correctIndex: 1, explanation: "Atomculuğun öncüsü Demokritos'tur (ve Leukippos)." },
  { id: "q_fel19_3", capsuleId: "fel19", category: "felsefe", question: "'Atom' sözcüğü ne anlama gelir?", options: ["Küçük", "Bölünemez", "Yuvarlak", "Ağır"], correctIndex: 1, explanation: "'Atom' Yunanca 'bölünemez' anlamına gelir." },
  { id: "q_fel19_4", capsuleId: "fel19", category: "felsefe", question: "Atomculuk hangi modern teoriye ilham vermiştir?", options: ["Görelilik teorisi", "Modern atom teorisi", "Evrim teorisi", "Büyük patlama"], correctIndex: 1, explanation: "Atomcuların görüşü, maddenin yapısına ilişkin modern atom teorisine ilham vermiştir." },
];
