import type { Question } from "./data";

// extraCapsules5 (eksik konular) için sorular — her konu 4 soru
export const questionsExtra10: Question[] = [
  // ztr1 Ünlü uyumları
  { id: "q_ztr1_1", capsuleId: "ztr1", category: "turkce", question: "Aşağıdaki sözcüklerden hangisi büyük ünlü uyumuna UYMAZ?", options: ["kalemlik", "kitap", "gözlükçü", "çocuklar"], correctIndex: 1, explanation: "'kitap' sözcüğünde kalın (a) ve ince (i) ünlüler bir arada olduğu için büyük ünlü uyumuna uymaz; Arapça kökenlidir." },
  { id: "q_ztr1_2", capsuleId: "ztr1", category: "turkce", question: "Küçük ünlü uyumu neye dayanır?", options: ["Kalınlık-incelik", "Düzlük-yuvarlaklık", "Sertlik-yumuşaklık", "Uzunluk-kısalık"], correctIndex: 1, explanation: "Küçük ünlü uyumu düzlük-yuvarlaklık kuralına dayanır; düz ünlüden sonra düz ünlü gelir." },
  { id: "q_ztr1_3", capsuleId: "ztr1", category: "turkce", question: "Aşağıdaki eklerden hangisi büyük ünlü uyumunu her zaman bozar?", options: ["-lar/-ler", "-yor", "-cı/-ci", "-dan/-den"], correctIndex: 1, explanation: "'-yor' eki tek biçimlidir ve büyük/küçük ünlü uyumunu bozar: 'geliyor' (i→o uymaz)." },
  { id: "q_ztr1_4", capsuleId: "ztr1", category: "turkce", question: "'Çamur' sözcüğü hangi uyuma uymaz?", options: ["Büyük ünlü uyumu", "Küçük ünlü uyumu", "Her ikisine de uyar", "Hiçbir uyuma girmez"], correctIndex: 1, explanation: "'Çamur'da yuvarlak 'u'dan önce düz 'a' geldiği için küçük ünlü uyumuna uymaz; büyük ünlü uyumuna (hep kalın) uyar." },

  // ztr2 Ses düşmesi-türemesi
  { id: "q_ztr2_1", capsuleId: "ztr2", category: "turkce", question: "'ağız' sözcüğüne '-ı' eki gelince oluşan 'ağzı' biçiminde hangi ses olayı vardır?", options: ["Ünsüz türemesi", "Ünlü düşmesi", "Ünsüz yumuşaması", "Kaynaşma"], correctIndex: 1, explanation: "'ağız → ağzı' değişiminde ikinci hecedeki dar ünlü 'ı' düşmüştür (ünlü düşmesi)." },
  { id: "q_ztr2_2", capsuleId: "ztr2", category: "turkce", question: "'his + etmek → hissetmek' örneğinde hangi ses olayı görülür?", options: ["Ünlü düşmesi", "Ünsüz türemesi (ikizleşme)", "Ünsüz düşmesi", "Ünlü daralması"], correctIndex: 1, explanation: "'hissetmek'te 's' ünsüzü ikizleşerek türemiştir; bu ünsüz türemesidir." },
  { id: "q_ztr2_3", capsuleId: "ztr2", category: "turkce", question: "'su + u → suyu' örneğindeki 'y' harfi ne görevdedir?", options: ["Yapım eki", "Kaynaştırma harfi", "Çekim eki", "Kök"], correctIndex: 1, explanation: "İki ünlünün yan yana gelmemesi için araya giren 'y' bir kaynaştırma harfidir." },
  { id: "q_ztr2_4", capsuleId: "ztr2", category: "turkce", question: "Aşağıdaki sözcüklerden hangisi yan yana ünlü içerdiği için yabancı kökenlidir?", options: ["kalem", "saat", "gözlük", "yaprak"], correctIndex: 1, explanation: "Türkçede iki ünlü yan yana gelmez; 'saat' (a-a) yan yana ünlü içerdiği için yabancı kökenlidir." },

  // ztr3 Büyük harf-kısaltma
  { id: "q_ztr3_1", capsuleId: "ztr3", category: "turkce", question: "Aşağıdaki cümlelerin hangisinde 'doğu' sözcüğü büyük harfle yazılmalıdır?", options: ["Evin doğusunda bahçe var.", "Güneş doğudan doğar.", "Doğu Anadolu çok yüksektir.", "Rüzgâr doğudan esiyor."], correctIndex: 2, explanation: "'Doğu Anadolu' bir bölge (özel ad) olduğu için büyük yazılır; diğerlerinde yön anlamındadır." },
  { id: "q_ztr3_2", capsuleId: "ztr3", category: "turkce", question: "Aşağıdaki kısaltmalardan hangisi yanlış yazılmıştır?", options: ["TBMM", "cm", "Kg", "TDK"], correctIndex: 2, explanation: "Kilogramın kısaltması küçük harfle 'kg' yazılır ve nokta almaz; 'Kg' yanlıştır." },
  { id: "q_ztr3_3", capsuleId: "ztr3", category: "turkce", question: "'Ankara'da' sözcüğündeki kesme işareti neden kullanılmıştır?", options: ["Cins isim olduğu için", "Özel ada gelen eki ayırmak için", "Kısaltma olduğu için", "Yanlış kullanılmıştır"], correctIndex: 1, explanation: "Özel adlara gelen çekim ekleri kesme işaretiyle ayrılır: 'Ankara'da'." },
  { id: "q_ztr3_4", capsuleId: "ztr3", category: "turkce", question: "Akrabalık adları ne zaman büyük harfle yazılır?", options: ["Her zaman", "Unvan veya lakap olarak kullanıldığında", "Cümle sonunda", "Asla"], correctIndex: 1, explanation: "Akrabalık adları unvan/lakap olmadıkça küçük yazılır; 'Ayşe Teyze' gibi unvan olunca büyük yazılır." },

  // ztr4 Birleşik sözcük
  { id: "q_ztr4_1", capsuleId: "ztr4", category: "turkce", question: "'kahve + altı' birleşmesiyle oluşan sözcük neden bitişik yazılır?", options: ["Anlam kayması ve ses düşmesi olduğu için", "İkileme olduğu için", "Deyim olduğu için", "Yardımcı fiil içerdiği için"], correctIndex: 0, explanation: "'kahvaltı'da hem ses düşmesi hem anlam kayması vardır; bu yüzden bitişik yazılır." },
  { id: "q_ztr4_2", capsuleId: "ztr4", category: "turkce", question: "Aşağıdakilerden hangisi ayrı yazılır?", options: ["bembeyaz", "hissetmek", "yavaş yavaş", "hanımeli"], correctIndex: 2, explanation: "İkilemeler daima ayrı yazılır: 'yavaş yavaş'." },
  { id: "q_ztr4_3", capsuleId: "ztr4", category: "turkce", question: "'yardım etmek' neden ayrı yazılır?", options: ["İkileme olduğu için", "Ses olayı (düşme/türeme) olmadığı için", "Deyim olduğu için", "Pekiştirme olduğu için"], correctIndex: 1, explanation: "Yardımcı fiille kurulan birleşik fiilde ses olayı yoksa ayrı yazılır: 'yardım etmek'. 'hissetmek'te ses olayı olduğu için bitişiktir." },
  { id: "q_ztr4_4", capsuleId: "ztr4", category: "turkce", question: "Aşağıdaki ikilemelerden hangisinin yazımı doğrudur?", options: ["ev ve bark", "çoluk, çocuk", "yavaş yavaş", "güzel-güzel"], correctIndex: 2, explanation: "İkilemeler arasına bağlaç, virgül veya çizgi girmez; ayrı ve boşlukla yazılır: 'yavaş yavaş'." },

  // ztr5 Sözel mantık
  { id: "q_ztr5_1", capsuleId: "ztr5", category: "turkce", question: "Sözel mantık sorularında bir yargının 'kesinlikle doğru' sayılması için ne gerekir?", options: ["Mantıklı görünmesi", "Verilenlerden çıkan tek olası sonuç olması", "Uzun olması", "İlk sırada olması"], correctIndex: 1, explanation: "Bir yargı, ancak verilen bilgilerin tek olası sonucuysa 'kesinlikle doğru'dur; başka ihtimal varsa kesin sayılmaz." },
  { id: "q_ztr5_2", capsuleId: "ztr5", category: "turkce", question: "Sıralama ve eşleştirme mantık sorularında en etkili çözüm yöntemi hangisidir?", options: ["Rastgele seçmek", "Tablo kurup kesin bilgileri işaretlemek", "En uzun seçeneği seçmek", "İlk cümleyi okumak"], correctIndex: 1, explanation: "Kesin bilgileri tabloya işleyip olasılıkları elemek, mantık sorularının en güvenilir çözüm yoludur." },
  { id: "q_ztr5_3", capsuleId: "ztr5", category: "turkce", question: "'A, B'den uzundur. B, C'den uzundur.' bilgilerine göre kesinlikle doğru olan hangisidir?", options: ["C en uzundur", "A en uzundur", "B en kısadır", "A ile C eşittir"], correctIndex: 1, explanation: "A>B ve B>C olduğundan A>B>C sıralaması çıkar; A kesinlikle en uzundur." },
  { id: "q_ztr5_4", capsuleId: "ztr5", category: "turkce", question: "Mantık sorularında 'olabilir' ifadesi ne anlama gelir?", options: ["Kesin doğrudur", "Kesin yanlıştır", "Verilenlere göre mümkün ama kesin değil", "Anlamsızdır"], correctIndex: 2, explanation: "'Olabilir', verilen bilgilerle çelişmeyen ama kesin de olmayan, mümkün bir durumu ifade eder." },

  // ztr6 Grafik-tablo
  { id: "q_ztr6_1", capsuleId: "ztr6", category: "turkce", question: "Grafik/tablo yorumlama sorularında en sık yapılan hata hangisidir?", options: ["Metni okumak", "Eksen birimlerini ve ölçeği okumadan görsele bakmak", "Seçenekleri okumak", "Soruyu iki kez okumak"], correctIndex: 1, explanation: "Bir eksen yüzde, diğeri adet olabilir; birimi ve ölçeği kaçırmak en sık yapılan hatadır." },
  { id: "q_ztr6_2", capsuleId: "ztr6", category: "turkce", question: "'Tabloya göre kesinlikle söylenebilir' tipi sorularda hangi bilgi doğru kabul edilir?", options: ["Tahmin edilen bilgiler", "Yalnız tabloda açıkça yer alan bilgiler", "Genel kültür bilgisi", "Yorum içeren ifadeler"], correctIndex: 1, explanation: "Yalnızca tabloda/grafikte açıkça bulunan bilgiler doğru kabul edilir; yorum ve tahminler elenir." },
  { id: "q_ztr6_3", capsuleId: "ztr6", category: "turkce", question: "Bir metni grafiğe aktarma sorusunda ilk adım ne olmalıdır?", options: ["Seçenekleri ezberlemek", "Metindeki sayısal ilişkileri (artış, azalış, oran) tespit etmek", "Grafiği çizmek", "Başlığı değiştirmek"], correctIndex: 1, explanation: "Önce metindeki sayısal ilişkiler belirlenir, sonra bu ilişkiler seçeneklerdeki grafiklerle karşılaştırılır." },
  { id: "q_ztr6_4", capsuleId: "ztr6", category: "turkce", question: "Grafik yorumlama becerisi neden önemlidir?", options: ["Yalnız matematik için", "Sayısal bilgiyi doğru okuyup yorumlamayı sağladığı için", "Sadece ezber için", "Hiçbir işe yaramaz"], correctIndex: 1, explanation: "Grafik/tablo yorumlama, sayısal bilgiyi doğru okuyup çıkarım yapma becerisidir ve birçok soru tipinde gereklidir." },

  // zmat1 Mantık önermeler
  { id: "q_zmat1_1", capsuleId: "zmat1", category: "matematik", question: "Aşağıdakilerden hangisi bir önermedir?", options: ["Kapıyı kapat!", "Bugün hava nasıl?", "Ankara Türkiye'nin başkentidir.", "Ne güzel bir gün!"], correctIndex: 2, explanation: "Önerme doğru ya da yanlış değeri alabilen yargıdır. 'Ankara başkenttir' doğru bir önermedir; emir, soru ve ünlem önerme değildir." },
  { id: "q_zmat1_2", capsuleId: "zmat1", category: "matematik", question: "p∧q (p ve q) bileşik önermesi ne zaman doğrudur?", options: ["En az biri doğruysa", "Yalnız ikisi de doğruysa", "İkisi de yanlışsa", "Biri yanlışsa"], correctIndex: 1, explanation: "'ve' (∧) bağlacı yalnız her iki önerme de doğruysa doğru değerini verir." },
  { id: "q_zmat1_3", capsuleId: "zmat1", category: "matematik", question: "p→q koşullu önermesi hangi durumda YANLIŞTIR?", options: ["p doğru, q doğru", "p doğru, q yanlış", "p yanlış, q doğru", "p yanlış, q yanlış"], correctIndex: 1, explanation: "Koşullu önerme yalnızca 'doğru ise yanlış' (p=1, q=0) durumunda yanlıştır." },
  { id: "q_zmat1_4", capsuleId: "zmat1", category: "matematik", question: "'p ise q' önermesine mantıkça denk olan hangisidir?", options: ["q ise p (karşıt)", "~p ise ~q (ters)", "~q ise ~p (karşıt ters)", "p ise ~q"], correctIndex: 2, explanation: "Bir koşullu önerme, karşıt tersiyle (~q→~p) mantıkça denktir; ikisinin doğruluk değeri hep aynıdır." },

  // zmat2 İstatistik
  { id: "q_zmat2_1", capsuleId: "zmat2", category: "matematik", question: "4, 6, 8, 10, 12 verilerinin aritmetik ortalaması kaçtır?", options: ["8", "10", "6", "40"], correctIndex: 0, explanation: "Toplam = 40, veri sayısı = 5; ortalama = 40/5 = 8." },
  { id: "q_zmat2_2", capsuleId: "zmat2", category: "matematik", question: "3, 7, 5, 9, 5, 2 verilerinin modu (tepe değeri) kaçtır?", options: ["3", "5", "7", "2"], correctIndex: 1, explanation: "En çok tekrar eden değer 5'tir (iki kez); mod 5'tir." },
  { id: "q_zmat2_3", capsuleId: "zmat2", category: "matematik", question: "2, 4, 6, 8 verilerinin ortancası (medyanı) kaçtır?", options: ["4", "5", "6", "20"], correctIndex: 1, explanation: "Veri sayısı çift olduğundan ortadaki iki değerin (4 ve 6) ortalaması alınır: (4+6)/2 = 5." },
  { id: "q_zmat2_4", capsuleId: "zmat2", category: "matematik", question: "Bir veri grubuna çok büyük bir aykırı değer eklenirse hangi ölçü en çok etkilenir?", options: ["Mod", "Medyan", "Aritmetik ortalama", "Hiçbiri"], correctIndex: 2, explanation: "Aritmetik ortalama tüm değerlere duyarlı olduğu için aykırı değerden en çok etkilenir; medyan daha az etkilenir." },

  // zmat3 Kâr-zarar
  { id: "q_zmat3_1", capsuleId: "zmat3", category: "matematik", question: "Maliyeti 200 TL olan bir ürün 250 TL'ye satılırsa yüzde kaç kâr edilir?", options: ["%20", "%25", "%50", "%15"], correctIndex: 1, explanation: "Kâr = 250 − 200 = 50 TL. Yüzde kâr = 50/200 × 100 = %25." },
  { id: "q_zmat3_2", capsuleId: "zmat3", category: "matematik", question: "Bir mal %25 kârla satılıp sonra %20 indirim yapılırsa ne olur?", options: ["%5 kâr edilir", "Tam maliyetine satılır (ne kâr ne zarar)", "%5 zarar edilir", "%45 kâr edilir"], correctIndex: 1, explanation: "1,25 × 0,80 = 1,00 olduğundan mal tam maliyet fiyatına satılır; ne kâr ne zarar vardır." },
  { id: "q_zmat3_3", capsuleId: "zmat3", category: "matematik", question: "Bir ürün 300 TL'ye alınıp 240 TL'ye satılırsa durum nedir?", options: ["%20 kâr", "%20 zarar", "%25 zarar", "%20 kâr"], correctIndex: 1, explanation: "Zarar = 300 − 240 = 60 TL. Yüzde zarar = 60/300 × 100 = %20." },
  { id: "q_zmat3_4", capsuleId: "zmat3", category: "matematik", question: "Yüzde kâr genellikle hangi tutar üzerinden hesaplanır?", options: ["Satış fiyatı", "Maliyet (alış) fiyatı", "Etiket fiyatı", "Kâr tutarı"], correctIndex: 1, explanation: "Yüzde kâr/zarar çoğunlukla maliyet (alış) fiyatı üzerinden hesaplanır." },

  // zmat4 Karışım
  { id: "q_zmat4_1", capsuleId: "zmat4", category: "matematik", question: "200 gram suda 50 gram tuz çözülürse karışımın kütlece tuz yüzdesi kaçtır?", options: ["%20", "%25", "%50", "%10"], correctIndex: 0, explanation: "Toplam karışım = 200 + 50 = 250 g. Tuz oranı = 50/250 × 100 = %20." },
  { id: "q_zmat4_2", capsuleId: "zmat4", category: "matematik", question: "Bir tuzlu su karışımına saf su eklenirse ne olur?", options: ["Tuz miktarı artar", "Tuz miktarı sabit kalır, derişim azalır", "Tuz miktarı azalır", "Derişim artar"], correctIndex: 1, explanation: "Su eklenince tuz (saf madde) miktarı değişmez, yalnız toplam artar; bu yüzden derişim azalır." },
  { id: "q_zmat4_3", capsuleId: "zmat4", category: "matematik", question: "Karışım problemlerinde hangi büyüklük her zaman korunur?", options: ["Toplam hacim", "Saf madde miktarı", "Yüzde derişim", "Sıcaklık"], correctIndex: 1, explanation: "Karışıma su eklense/buharlaşsa da saf madde (tuz, şeker) miktarı korunur; hesap bu sabit üzerinden kurulur." },
  { id: "q_zmat4_4", capsuleId: "zmat4", category: "matematik", question: "Tuzlu su kaynatılıp bir miktar suyu buharlaştırılırsa ne olur?", options: ["Tuz miktarı azalır", "Derişim (tuz oranı) artar", "Derişim azalır", "Hiçbir şey değişmez"], correctIndex: 1, explanation: "Su buharlaşınca tuz miktarı sabit kalır ama toplam azaldığı için tuz oranı (derişim) artar." },

  // zmat5 Sayı problemleri
  { id: "q_zmat5_1", capsuleId: "zmat5", category: "matematik", question: "Bir sayının 3 katının 5 fazlası 26 ise sayı kaçtır?", options: ["6", "7", "8", "9"], correctIndex: 1, explanation: "3x + 5 = 26 → 3x = 21 → x = 7." },
  { id: "q_zmat5_2", capsuleId: "zmat5", category: "matematik", question: "Ardışık üç tam sayının toplamı 45 ise en büyüğü kaçtır?", options: ["14", "15", "16", "17"], correctIndex: 2, explanation: "Ortadaki sayı 45/3 = 15; sayılar 14, 15, 16'dır. En büyüğü 16'dır." },
  { id: "q_zmat5_3", capsuleId: "zmat5", category: "matematik", question: "İki basamaklı bir sayının rakamları toplamı 9 ise bu sayı hangisine kesin bölünür?", options: ["7", "9", "11", "4"], correctIndex: 1, explanation: "Rakamları toplamı 9'un katı (burada 9) olan sayılar 9'a tam bölünür." },
  { id: "q_zmat5_4", capsuleId: "zmat5", category: "matematik", question: "Bir sayının yarısı ile üçte birinin toplamı 25 ise sayı kaçtır?", options: ["30", "25", "20", "36"], correctIndex: 0, explanation: "x/2 + x/3 = 25 → 5x/6 = 25 → x = 30." },

  // zmat6 Faiz
  { id: "q_zmat6_1", capsuleId: "zmat6", category: "matematik", question: "1000 TL, yıllık %10 basit faizle 2 yıl işletilirse faiz kaç TL olur?", options: ["100", "200", "220", "300"], correctIndex: 1, explanation: "Faiz = 1000 × 0,10 × 2 = 200 TL." },
  { id: "q_zmat6_2", capsuleId: "zmat6", category: "matematik", question: "Basit faizde faiz hangi formülle hesaplanır?", options: ["Anapara + oran", "Anapara × oran × süre", "Anapara / süre", "Anapara × süre"], correctIndex: 1, explanation: "Basit faiz = Anapara × Faiz oranı × Süre formülüyle bulunur." },
  { id: "q_zmat6_3", capsuleId: "zmat6", category: "matematik", question: "2000 TL yıllık %5 faizle 6 ay işletilirse faiz kaç TL olur?", options: ["50", "100", "200", "25"], correctIndex: 0, explanation: "6 ay = 0,5 yıl. Faiz = 2000 × 0,05 × 0,5 = 50 TL." },
  { id: "q_zmat6_4", capsuleId: "zmat6", category: "matematik", question: "Bileşik faizin basit faizden farkı nedir?", options: ["Her dönem faiz anaparaya eklenir, faizin faizi kazanılır", "Süre hesaba katılmaz", "Faiz oranı sabit değildir", "Anapara azalır"], correctIndex: 0, explanation: "Bileşik faizde her dönemin faizi anaparaya eklenir ve sonraki faiz büyüyen tutar üzerinden hesaplanır (faizin faizi)." },

  // zgeo1 Yamuk
  { id: "q_zgeo1_1", capsuleId: "zgeo1", category: "geometri", question: "Paralel kenarları 8 ve 12, yüksekliği 5 olan yamuğun alanı kaçtır?", options: ["50", "40", "60", "100"], correctIndex: 0, explanation: "Alan = [(a+c)/2]·h = [(8+12)/2]·5 = 10·5 = 50." },
  { id: "q_zgeo1_2", capsuleId: "zgeo1", category: "geometri", question: "Yamuğun orta tabanı neye eşittir?", options: ["Paralel kenarların farkı", "Paralel kenarların ortalaması (a+c)/2", "Yüksekliğe", "Köşegene"], correctIndex: 1, explanation: "Orta taban, paralel kenarların (alt ve üst taban) aritmetik ortalamasına eşittir: (a+c)/2." },
  { id: "q_zgeo1_3", capsuleId: "zgeo1", category: "geometri", question: "İkizkenar yamukta aşağıdakilerden hangisi doğrudur?", options: ["Tüm kenarlar eşittir", "Köşegenler eşittir", "Tüm açılar 90°'dir", "Paralel kenar yoktur"], correctIndex: 1, explanation: "İkizkenar yamukta paralel olmayan kenarlar, taban açıları ve köşegenler birbirine eşittir." },
  { id: "q_zgeo1_4", capsuleId: "zgeo1", category: "geometri", question: "Yamuk hangi dörtgen türüdür?", options: ["İki çift kenarı paralel", "Yalnız bir çift kenarı paralel", "Hiçbir kenarı paralel değil", "Tüm kenarları eşit"], correctIndex: 1, explanation: "Yamuk, yalnızca bir çift karşılıklı kenarı paralel olan dörtgendir." },

  // zgeo2 Birim çember
  { id: "q_zgeo2_1", capsuleId: "zgeo2", category: "geometri", question: "Birim çemberde bir açının bitim noktasının koordinatları neyi verir?", options: ["(sinθ, cosθ)", "(cosθ, sinθ)", "(tanθ, cotθ)", "(θ, θ)"], correctIndex: 1, explanation: "Birim çemberde bitim noktasının x koordinatı cosθ, y koordinatı sinθ'dır: (cosθ, sinθ)." },
  { id: "q_zgeo2_2", capsuleId: "zgeo2", category: "geometri", question: "sin²θ + cos²θ ifadesi neye eşittir?", options: ["0", "1", "2", "tanθ"], correctIndex: 1, explanation: "Temel trigonometrik özdeşlik: sin²θ + cos²θ = 1." },
  { id: "q_zgeo2_3", capsuleId: "zgeo2", category: "geometri", question: "II. bölgede (90°-180°) hangi trigonometrik oran pozitiftir?", options: ["Yalnız sinüs", "Yalnız kosinüs", "Yalnız tanjant", "Hepsi"], correctIndex: 0, explanation: "II. bölgede yalnızca sinüs pozitiftir (y koordinatı +, x koordinatı −)." },
  { id: "q_zgeo2_4", capsuleId: "zgeo2", category: "geometri", question: "180° kaç radyandır?", options: ["π/2", "π", "2π", "π/4"], correctIndex: 1, explanation: "180° = π radyandır; bu, derece-radyan dönüşümünün temel eşitliğidir." },

  // zgeo3 Piramit
  { id: "q_zgeo3_1", capsuleId: "zgeo3", category: "geometri", question: "Taban alanı 12, yüksekliği 5 olan piramidin hacmi kaçtır?", options: ["20", "60", "30", "17"], correctIndex: 0, explanation: "V = (1/3)·taban alanı·yükseklik = (1/3)·12·5 = 20." },
  { id: "q_zgeo3_2", capsuleId: "zgeo3", category: "geometri", question: "Piramidin hacmi, aynı taban ve yüksekliğe sahip prizmanın kaçta kaçıdır?", options: ["1/2", "1/3", "2/3", "Eşittir"], correctIndex: 1, explanation: "Piramidin hacmi, aynı taban ve yüksekliğe sahip prizmanın üçte biridir." },
  { id: "q_zgeo3_3", capsuleId: "zgeo3", category: "geometri", question: "Düzgün piramitte tepe noktası nerededir?", options: ["Bir kenarın üstünde", "Taban merkezinin tam üstünde", "Tabanın dışında", "Yan yüzde"], correctIndex: 1, explanation: "Düzgün piramitte tepe noktası, taban merkezinin tam üzerinde yer alır." },
  { id: "q_zgeo3_4", capsuleId: "zgeo3", category: "geometri", question: "Kare piramidin yanal yüzleri nasıl üçgenlerdir?", options: ["Dik üçgen", "Eş ikizkenar üçgen", "Çeşitkenar üçgen", "Eşkenar dörtgen"], correctIndex: 1, explanation: "Düzgün kare piramitte yanal yüzler birbirine eş (özdeş) ikizkenar üçgenlerdir." },

  // zfiz1 Çembersel hareket
  { id: "q_zfiz1_1", capsuleId: "zfiz1", category: "fizik", question: "Düzgün çembersel harekette ivme hangi yöne doğrudur?", options: ["Hareket yönünde", "Merkeze doğru (merkezcil)", "Merkezden dışa", "Yukarı"], correctIndex: 1, explanation: "Düzgün çembersel harekette ivme daima merkeze yöneliktir; buna merkezcil ivme denir (a = v²/r)." },
  { id: "q_zfiz1_2", capsuleId: "zfiz1", category: "fizik", question: "Sabit süratle dönen bir cisim neden ivmeli harekettedir?", options: ["Sürati arttığı için", "Hızının yönü sürekli değiştiği için", "Kütlesi arttığı için", "Durduğu için"], correctIndex: 1, explanation: "Sürat sabit olsa da hızın yönü sürekli değiştiğinden hareket ivmelidir." },
  { id: "q_zfiz1_3", capsuleId: "zfiz1", category: "fizik", question: "Periyot (T) ile frekans (f) arasındaki ilişki nedir?", options: ["f = T", "f = 1/T", "f = 2T", "f = T²"], correctIndex: 1, explanation: "Frekans, periyodun tersidir: f = 1/T (birim zamandaki tur sayısı)." },
  { id: "q_zfiz1_4", capsuleId: "zfiz1", category: "fizik", question: "Merkezcil kuvvet hangi formülle hesaplanır?", options: ["F = m·g", "F = m·v²/r", "F = m·a·t", "F = V·I"], correctIndex: 1, explanation: "Merkezcil kuvvet F = m·v²/r'dir; cismi çember üzerinde tutan, merkeze yönelik kuvvettir." },

  // zfiz2 Kütle çekim
  { id: "q_zfiz2_1", capsuleId: "zfiz2", category: "fizik", question: "İki cisim arasındaki uzaklık iki katına çıkarsa kütle çekim kuvveti nasıl değişir?", options: ["Yarıya iner", "Dörtte bire iner", "İki katına çıkar", "Değişmez"], correctIndex: 1, explanation: "Kuvvet uzaklığın karesiyle ters orantılıdır; uzaklık 2 katına çıkınca kuvvet 1/2²=1/4'e iner." },
  { id: "q_zfiz2_2", capsuleId: "zfiz2", category: "fizik", question: "Kütle çekim kuvveti kütlelerle nasıl bir ilişki içindedir?", options: ["Ters orantılı", "Doğru orantılı", "İlgisiz", "Karesiyle ters"], correctIndex: 1, explanation: "F = G·m₁·m₂/d² olduğundan kuvvet, kütlelerin çarpımıyla doğru orantılıdır." },
  { id: "q_zfiz2_3", capsuleId: "zfiz2", category: "fizik", question: "Bir cismin ağırlığı aslında nedir?", options: ["Kütlesi", "Dünya'nın ona uyguladığı çekim kuvveti", "Hacmi", "Yoğunluğu"], correctIndex: 1, explanation: "Ağırlık, Dünya'nın (veya bir gök cisminin) cisme uyguladığı kütle çekim kuvvetidir." },
  { id: "q_zfiz2_4", capsuleId: "zfiz2", category: "fizik", question: "Yükseklik arttıkça yer çekimi ivmesi (g) nasıl değişir?", options: ["Artar", "Azalır", "Değişmez", "İki katına çıkar"], correctIndex: 1, explanation: "Yerden uzaklaştıkça (yükseklik arttıkça) çekim zayıflar; g azalır." },

  // zfiz3 Isıl genleşme
  { id: "q_zfiz3_1", capsuleId: "zfiz3", category: "fizik", question: "Maddeler ısındığında genellikle ne olur?", options: ["Büzülür", "Genleşir (hacmi artar)", "Kütlesi artar", "Yok olur"], correctIndex: 1, explanation: "Isınan maddede tanecikler daha hızlı titreşir, aralarındaki mesafe artar; madde genleşir." },
  { id: "q_zfiz3_2", capsuleId: "zfiz3", category: "fizik", question: "Aşağıdakilerden hangisi en çok genleşir?", options: ["Katılar", "Sıvılar", "Gazlar", "Hepsi eşit"], correctIndex: 2, explanation: "Genleşme miktarı gazlarda en fazla, sıvılarda orta, katılarda en azdır." },
  { id: "q_zfiz3_3", capsuleId: "zfiz3", category: "fizik", question: "Demir yolu raylarının aralarına neden boşluk bırakılır?", options: ["Ses için", "Isıl genleşmede rayların bükülmemesi için", "Süs için", "Hız için"], correctIndex: 1, explanation: "Raylar sıcakta genleşir; boşluk bırakılmazsa genleşen raylar birbirini iterek bükülür." },
  { id: "q_zfiz3_4", capsuleId: "zfiz3", category: "fizik", question: "Su hangi sıcaklıkta en yoğundur?", options: ["0°C", "4°C", "100°C", "-4°C"], correctIndex: 1, explanation: "Su 4°C'de en yoğundur; bu anormal davranış sayesinde göller dipten değil yüzeyden donar." },

  // zfiz4 Elektrik devreleri
  { id: "q_zfiz4_1", capsuleId: "zfiz4", category: "fizik", question: "Seri bağlı bir devrede aşağıdakilerden hangisi her yerde aynıdır?", options: ["Gerilim", "Akım", "Direnç", "Güç"], correctIndex: 1, explanation: "Seri devrede akım her noktada aynıdır; gerilim dirençler arasında paylaşılır." },
  { id: "q_zfiz4_2", capsuleId: "zfiz4", category: "fizik", question: "Paralel bağlı dirençlerde toplam direnç için ne söylenir?", options: ["Dirençlerin toplamına eşittir", "En küçük dirençten de küçüktür", "En büyük dirence eşittir", "Sıfırdır"], correctIndex: 1, explanation: "Paralel bağlamada eşdeğer direnç, kollardaki en küçük dirençten bile daha küçük olur." },
  { id: "q_zfiz4_3", capsuleId: "zfiz4", category: "fizik", question: "Evlerdeki prizler neden paralel bağlıdır?", options: ["Daha ucuz olduğu için", "Bir cihaz kapanınca diğerleri çalışmaya devam etsin diye", "Daha az akım için", "Zorunluluktan"], correctIndex: 1, explanation: "Paralel bağlamada her cihazın gerilimi aynıdır ve biri kapanınca diğerleri çalışmaya devam eder." },
  { id: "q_zfiz4_4", capsuleId: "zfiz4", category: "fizik", question: "Seri bağlı 2Ω ve 4Ω dirençlerin eşdeğeri kaç ohm'dur?", options: ["6", "1,33", "2", "8"], correctIndex: 0, explanation: "Seri bağlamada dirençler toplanır: 2 + 4 = 6 Ω." },

  // zkim1 Tepkime enerjisi
  { id: "q_zkim1_1", capsuleId: "zkim1", category: "kimya", question: "Isı açığa çıkaran (çevreyi ısıtan) tepkimeye ne denir?", options: ["Endotermik", "Ekzotermik", "Nötr", "Tersinir"], correctIndex: 1, explanation: "Isı veren tepkime ekzotermiktir (ΔH<0); yanma ve nötrleşme buna örnektir." },
  { id: "q_zkim1_2", capsuleId: "zkim1", category: "kimya", question: "Bir tepkimede ΔH pozitif ise tepkime nasıldır?", options: ["Ekzotermik", "Endotermik (ısı alır)", "Kendiliğinden olur", "Enerji açığa çıkarır"], correctIndex: 1, explanation: "ΔH pozitifse tepkime ısı soğurur, yani endotermiktir; çevre soğur." },
  { id: "q_zkim1_3", capsuleId: "zkim1", category: "kimya", question: "Fotosentez enerji açısından nasıl bir tepkimedir?", options: ["Ekzotermik", "Endotermik", "Nötr", "Redoks değil"], correctIndex: 1, explanation: "Fotosentez ışık enerjisini soğurarak gerçekleşir; endotermik bir tepkimedir." },
  { id: "q_zkim1_4", capsuleId: "zkim1", category: "kimya", question: "Bir tepkimenin başlaması için gereken en düşük enerjiye ne denir?", options: ["Bağ enerjisi", "Aktivasyon enerjisi", "Potansiyel enerji", "Isı enerjisi"], correctIndex: 1, explanation: "Tepkimenin başlaması için gereken en düşük enerjiye aktivasyon enerjisi denir." },

  // zkim2 Kimyasal denge
  { id: "q_zkim2_1", capsuleId: "zkim2", category: "kimya", question: "Kimyasal denge ne zaman kurulur?", options: ["Tepkime durunca", "İleri ve geri tepkime hızları eşitlenince", "Ürün bitince", "Sıcaklık sıfır olunca"], correctIndex: 1, explanation: "İleri ve geri tepkime hızlarının eşitlendiği durumda dinamik denge kurulur; derişimler sabitlenir." },
  { id: "q_zkim2_2", capsuleId: "zkim2", category: "kimya", question: "Dengedeki bir sisteme ürün eklenirse denge hangi yöne kayar?", options: ["Ürünler yönüne", "Girenler yönüne", "Kaymaz", "Sisteme bağlı değil"], correctIndex: 1, explanation: "Le Chatelier ilkesine göre ürün artınca sistem bu etkiyi azaltmak için girenler yönüne kayar." },
  { id: "q_zkim2_3", capsuleId: "zkim2", category: "kimya", question: "Kimyasal denge 'dinamik'tir. Bu ne demektir?", options: ["Tepkime tamamen durur", "İki yönlü tepkime sürer ama derişimler sabit kalır", "Madde yok olur", "Sıcaklık sürekli artar"], correctIndex: 1, explanation: "Dengede tepkime durmaz; ileri ve geri yönde eşit hızda sürer ve derişimler değişmez." },
  { id: "q_zkim2_4", capsuleId: "zkim2", category: "kimya", question: "Dengedeki sistemin dışarıdan gelen etkiye tepki verme ilkesi hangisidir?", options: ["Avogadro ilkesi", "Le Chatelier ilkesi", "Pascal ilkesi", "Arşimet ilkesi"], correctIndex: 1, explanation: "Le Chatelier ilkesi, dengedeki sistemin dış etkiyi azaltacak yönde kaydığını ifade eder." },

  // zkim3 Tepkime hızı
  { id: "q_zkim3_1", capsuleId: "zkim3", category: "kimya", question: "Aşağıdakilerden hangisi tepkime hızını artırmaz?", options: ["Sıcaklık artışı", "Derişim artışı", "Yüzey alanının artması", "Sıcaklığın düşürülmesi"], correctIndex: 3, explanation: "Sıcaklığın düşmesi tanecik hareketini yavaşlatır ve tepkime hızını azaltır." },
  { id: "q_zkim3_2", capsuleId: "zkim3", category: "kimya", question: "Katalizör tepkimeyi nasıl hızlandırır?", options: ["Sıcaklığı artırarak", "Aktivasyon enerjisini düşürerek", "Ürünü artırarak", "Dengeyi kaydırarak"], correctIndex: 1, explanation: "Katalizör, aktivasyon enerjisini düşürerek tepkimeyi hızlandırır; kendisi tükenmez ve dengeyi kaydırmaz." },
  { id: "q_zkim3_3", capsuleId: "zkim3", category: "kimya", question: "Bir katı, toz hâline getirilirse tepkime hızı neden artar?", options: ["Kütlesi arttığı için", "Temas yüzeyi arttığı için", "Sıcaklığı arttığı için", "Rengi değiştiği için"], correctIndex: 1, explanation: "Toz hâlinde temas yüzeyi çok arttığı için daha fazla etkin çarpışma olur ve hız artar." },
  { id: "q_zkim3_4", capsuleId: "zkim3", category: "kimya", question: "Çarpışma teorisine göre bir tepkimenin gerçekleşmesi için tanecikler nasıl çarpışmalıdır?", options: ["Yalnız temas ederek", "Yeterli enerji ve uygun yönle", "Yavaşça", "Rastgele herhangi bir şekilde"], correctIndex: 1, explanation: "Çarpışma teorisine göre tanecikler yeterli enerjiyle ve uygun yönle (etkin çarpışma) çarpışmalıdır." },

  // zkim4 Elektrokimya
  { id: "q_zkim4_1", capsuleId: "zkim4", category: "kimya", question: "Bir pilde yükseltgenmenin gerçekleştiği elektrot hangisidir?", options: ["Katot (+)", "Anot (−)", "İletken", "Elektrolit"], correctIndex: 1, explanation: "Pilde yükseltgenme anotta (−) gerçekleşir; indirgenme ise katotta (+) olur." },
  { id: "q_zkim4_2", capsuleId: "zkim4", category: "kimya", question: "Pil, hangi enerji dönüşümünü gerçekleştirir?", options: ["Elektrik → ısı", "Kimyasal → elektrik", "Işık → kimyasal", "Isı → ışık"], correctIndex: 1, explanation: "Pil, kendiliğinden gerçekleşen redoks tepkimesiyle kimyasal enerjiyi elektrik enerjisine çevirir." },
  { id: "q_zkim4_3", capsuleId: "zkim4", category: "kimya", question: "Elektroliz, pilden nasıl farklıdır?", options: ["Kendiliğinden olur", "Dışarıdan elektrik vererek tepkimeyi zorlar", "Enerji üretir", "Redoks değildir"], correctIndex: 1, explanation: "Elektroliz, dışarıdan elektrik enerjisi vererek kendiliğinden olmayan tepkimeyi gerçekleştirir (kaplama, saflaştırma)." },
  { id: "q_zkim4_4", capsuleId: "zkim4", category: "kimya", question: "Pilde elektronlar hangi yönde akar?", options: ["Katottan anoda", "Anottan katoda", "Akmaz", "Elektrolit içinde"], correctIndex: 1, explanation: "Dış devrede elektronlar anottan (−) katoda (+) doğru akar." },

  // zkim5 Türler arası etkileşim
  { id: "q_zkim5_1", capsuleId: "zkim5", category: "kimya", question: "Aşağıdakilerden hangisi güçlü etkileşim (kimyasal bağ) değildir?", options: ["İyonik bağ", "Kovalent bağ", "Hidrojen bağı", "Metalik bağ"], correctIndex: 2, explanation: "Hidrojen bağı bir zayıf (moleküller arası) etkileşimdir; iyonik, kovalent ve metalik bağ güçlü etkileşimlerdir." },
  { id: "q_zkim5_2", capsuleId: "zkim5", category: "kimya", question: "Zayıf etkileşimlerin en güçlüsü hangisidir?", options: ["London kuvvetleri", "Hidrojen bağı", "Dipol-dipol", "İyonik bağ"], correctIndex: 1, explanation: "Moleküller arası (zayıf) etkileşimlerin en güçlüsü hidrojen bağıdır." },
  { id: "q_zkim5_3", capsuleId: "zkim5", category: "kimya", question: "Hidrojen bağı hangi durumda oluşur?", options: ["H, herhangi bir atoma bağlıysa", "H; F, O veya N gibi elektronegatif atomlara bağlıysa", "Yalnız metallerde", "Yalnız gazlarda"], correctIndex: 1, explanation: "Hidrojen bağı, H atomunun çok elektronegatif atomlara (F, O, N) bağlı olduğu durumda oluşur." },
  { id: "q_zkim5_4", capsuleId: "zkim5", category: "kimya", question: "Bir maddenin kaynama noktası neyle doğru orantılıdır?", options: ["Rengiyle", "Moleküller arası etkileşimlerin gücüyle", "Kütlesiyle her zaman", "Şekliyle"], correctIndex: 1, explanation: "Moleküller arası etkileşim ne kadar güçlüyse kaynama/erime noktası o kadar yüksektir." },

  // zbiyo1 Destek-hareket
  { id: "q_zbiyo1_1", capsuleId: "zbiyo1", category: "biyoloji", question: "Kaslar iş yaparken nasıl davranır?", options: ["Yalnızca uzayarak (iterek)", "Yalnızca kasılarak (çekerek)", "Hem itip hem çekerek", "Hareketsiz kalarak"], correctIndex: 1, explanation: "Kaslar yalnızca kasılarak (kısalıp çekerek) iş yapar; bu yüzden çift (antagonist) çalışırlar." },
  { id: "q_zbiyo1_2", capsuleId: "zbiyo1", category: "biyoloji", question: "İç organlarda bulunan, istem dışı çalışan kas türü hangisidir?", options: ["Çizgili kas", "Düz kas", "Kalp kası", "İskelet kası"], correctIndex: 1, explanation: "Düz kaslar iç organlarda bulunur ve istem dışı (otonom) çalışır." },
  { id: "q_zbiyo1_3", capsuleId: "zbiyo1", category: "biyoloji", question: "Aşağıdakilerden hangisi iskeletin görevlerinden biri değildir?", options: ["Vücuda destek olma", "İç organları koruma", "Besinleri sindirme", "Kan hücresi üretimi"], correctIndex: 2, explanation: "Sindirim iskeletin görevi değildir; iskelet destek, koruma, hareket ve kan hücresi üretimi sağlar." },
  { id: "q_zbiyo1_4", capsuleId: "zbiyo1", category: "biyoloji", question: "Diz ve dirsek gibi hareket açısı geniş eklemler hangi türdendir?", options: ["Oynamaz eklem", "Yarı oynar eklem", "Oynar eklem", "Kaynaşmış eklem"], correctIndex: 2, explanation: "Diz ve dirsek geniş hareket sağlayan oynar eklemlerdir; kafatası oynamaz eklemdir." },

  // zbiyo2 Duyu organları
  { id: "q_zbiyo2_1", capsuleId: "zbiyo2", category: "biyoloji", question: "Gözde görmenin en net olduğu bölge hangisidir?", options: ["Kör nokta", "Sarı benek", "Göz bebeği", "Kornea"], correctIndex: 1, explanation: "Sarı benek, görme reseptörlerinin en yoğun olduğu ve görüntünün en net oluştuğu bölgedir." },
  { id: "q_zbiyo2_2", capsuleId: "zbiyo2", category: "biyoloji", question: "Hem işitme hem denge görevini üstlenen duyu organı hangisidir?", options: ["Göz", "Kulak", "Burun", "Dil"], correctIndex: 1, explanation: "Kulak, işitmenin yanı sıra yarım daire kanalları sayesinde denge organı olarak da çalışır." },
  { id: "q_zbiyo2_3", capsuleId: "zbiyo2", category: "biyoloji", question: "Deri hangi duyuları algılar?", options: ["Yalnız dokunma", "Dokunma, basınç, sıcaklık ve ağrı", "Yalnız sıcaklık", "Yalnız ağrı"], correctIndex: 1, explanation: "Deri; dokunma, basınç, sıcaklık ve ağrı reseptörleri taşıyan çok yönlü bir duyu organıdır." },
  { id: "q_zbiyo2_4", capsuleId: "zbiyo2", category: "biyoloji", question: "Duyu organlarından gelen bilgiler nerede yorumlanır?", options: ["Duyu organının kendisinde", "Beyinde", "Omurilikte", "Kaslarda"], correctIndex: 1, explanation: "Duyu organları uyarıyı sinyale çevirir; asıl yorumlama (görme, işitme) beyinde gerçekleşir." },

  // zbiyo3 Üreme-gelişim
  { id: "q_zbiyo3_1", capsuleId: "zbiyo3", category: "biyoloji", question: "Yumurta ve spermin birleşmesiyle oluşan hücreye ne denir?", options: ["Gamet", "Zigot", "Embriyo", "Doku"], correctIndex: 1, explanation: "Döllenme sonucu oluşan ilk hücre zigottur; 2n (diploit) kromozomludur." },
  { id: "q_zbiyo3_2", capsuleId: "zbiyo3", category: "biyoloji", question: "Üreme hücreleri (gametler) hangi bölünmeyle oluşur?", options: ["Mitoz", "Mayoz", "İkiye bölünme", "Tomurcuklanma"], correctIndex: 1, explanation: "Gametler mayoz bölünmeyle oluşur; bu yüzden n (haploit) kromozomludurlar." },
  { id: "q_zbiyo3_3", capsuleId: "zbiyo3", category: "biyoloji", question: "Anne ile bebek arasında madde alışverişini sağlayan yapı hangisidir?", options: ["Plasenta", "Zigot", "Yumurta", "Böbrek"], correctIndex: 0, explanation: "Plasenta, anne ile bebek arasında besin-oksijen ve atık alışverişini sağlar." },
  { id: "q_zbiyo3_4", capsuleId: "zbiyo3", category: "biyoloji", question: "Zigot hangi bölünmeyle çoğalıp embriyoyu oluşturur?", options: ["Mayoz", "Mitoz", "Döllenme", "Fermantasyon"], correctIndex: 1, explanation: "Zigot mitoz bölünmelerle çoğalarak embriyoyu ve sonunda yeni bireyi oluşturur." },

  // zbiyo4 Bitkilerde taşıma
  { id: "q_zbiyo4_1", capsuleId: "zbiyo4", category: "biyoloji", question: "Kökten alınan su ve mineralleri yapraklara taşıyan iletim dokusu hangisidir?", options: ["Floem", "Ksilem", "Epidermis", "Kambiyum"], correctIndex: 1, explanation: "Ksilem (odun borusu), su ve mineralleri kökten yapraklara doğru tek yönlü taşır." },
  { id: "q_zbiyo4_2", capsuleId: "zbiyo4", category: "biyoloji", question: "Fotosentezle üretilen besini bitkinin her yerine taşıyan doku hangisidir?", options: ["Ksilem", "Floem", "Stoma", "Kök"], correctIndex: 1, explanation: "Floem (soymuk borusu), yapraklarda üretilen besini çift yönlü olarak bitkinin her yerine taşır." },
  { id: "q_zbiyo4_3", capsuleId: "zbiyo4", category: "biyoloji", question: "Yapraklardaki gözeneklerden (stoma) su buharı kaybına ne denir?", options: ["Terleme", "Fotosentez", "Solunum", "Emilim"], correctIndex: 0, explanation: "Terleme, yapraktaki stomalardan su buharı kaybıdır ve suyun yukarı çekilmesini sağlar." },
  { id: "q_zbiyo4_4", capsuleId: "zbiyo4", category: "biyoloji", question: "Uzun ağaçlarda suyun yukarı çıkmasını sağlayan temel mekanizma nedir?", options: ["Basınçlı pompa", "Terleme-kohezyon-gerilim", "Yer çekimi", "Rüzgâr"], correctIndex: 1, explanation: "Yapraklardan buharlaşan su, alttaki su sütununu yukarı çeker (kohezyon-gerilim mekanizması)." },

  // zbiyo5 Solunum-fermantasyon
  { id: "q_zbiyo5_1", capsuleId: "zbiyo5", category: "biyoloji", question: "Oksijenli solunum hücrede hangi organelde gerçekleşir?", options: ["Ribozom", "Mitokondri", "Kloroplast", "Çekirdek"], correctIndex: 1, explanation: "Oksijenli solunum mitokondride gerçekleşir ve çok sayıda ATP üretir." },
  { id: "q_zbiyo5_2", capsuleId: "zbiyo5", category: "biyoloji", question: "Oksijenli solunum ile fermantasyonun ATP verimi nasıldır?", options: ["İkisi de eşit", "Oksijenli çok, fermantasyon az ATP üretir", "Fermantasyon daha çok üretir", "İkisi de üretmez"], correctIndex: 1, explanation: "Oksijenli solunum bir glikozdan ~30-32 ATP üretirken, fermantasyon yalnızca 2 ATP üretir." },
  { id: "q_zbiyo5_3", capsuleId: "zbiyo5", category: "biyoloji", question: "Egzersizde kaslarda biriken ve yorgunluk hissi veren madde hangi fermantasyonla oluşur?", options: ["Etil alkol fermantasyonu", "Laktik asit fermantasyonu", "Fotosentez", "Oksijenli solunum"], correctIndex: 1, explanation: "Kaslar yeterli oksijen bulamayınca laktik asit fermantasyonu yapar; biriken laktik asit yanma/ağrı hissi verir." },
  { id: "q_zbiyo5_4", capsuleId: "zbiyo5", category: "biyoloji", question: "Ekmeğin kabarmasını sağlayan maya fermantasyonunda açığa çıkan gaz hangisidir?", options: ["Oksijen", "Karbondioksit", "Azot", "Hidrojen"], correctIndex: 1, explanation: "Maya (etil alkol) fermantasyonunda açığa çıkan karbondioksit gazı hamuru kabartır." },

  // zbiyo6 Komünite ekolojisi
  { id: "q_zbiyo6_1", capsuleId: "zbiyo6", category: "biyoloji", question: "Arı ile çiçek arasındaki, her iki tarafın da yarar gördüğü ilişki türü nedir?", options: ["Parazitlik", "Mutualizm", "Kommensalizm", "Rekabet"], correctIndex: 1, explanation: "Arı nektar bulur, çiçek tozlaşır; her iki tür de yarar gördüğü için bu ilişki mutualizmdir." },
  { id: "q_zbiyo6_2", capsuleId: "zbiyo6", category: "biyoloji", question: "Bir türün yarar, diğerinin zarar gördüğü ortak yaşam türü hangisidir?", options: ["Mutualizm", "Kommensalizm", "Parazitlik", "Avcılık"], correctIndex: 2, explanation: "Parazitlikte bir tür (parazit) yarar görürken diğeri (konak) zarar görür." },
  { id: "q_zbiyo6_3", capsuleId: "zbiyo6", category: "biyoloji", question: "Aynı kaynağı kullanan türler arasında görülen ilişki hangisidir?", options: ["Rekabet", "Mutualizm", "Kommensalizm", "Nötr"], correctIndex: 0, explanation: "Aynı besin, alan gibi kaynakları kullanan türler arasında rekabet ilişkisi oluşur." },
  { id: "q_zbiyo6_4", capsuleId: "zbiyo6", category: "biyoloji", question: "Bir ekosistemin zamanla değişip olgun (klimaks) topluluğa ulaşmasına ne denir?", options: ["Süksesyon", "Mutasyon", "Adaptasyon", "Rekabet"], correctIndex: 0, explanation: "Ekosistemin zaman içinde değişip kararlı (klimaks) topluluğa ulaşmasına süksesyon denir." },

  // ztar1 İslam tarihi
  { id: "q_ztar1_1", capsuleId: "ztar1", category: "tarih", question: "İslam takviminin başlangıcı sayılan olay hangisidir?", options: ["İslamiyet'in doğuşu", "Hicret (Mekke'den Medine'ye göç)", "Bedir Savaşı", "Mekke'nin fethi"], correctIndex: 1, explanation: "622'deki Hicret (Medine'ye göç) İslam (Hicri) takviminin başlangıcı kabul edilir." },
  { id: "q_ztar1_2", capsuleId: "ztar1", category: "tarih", question: "Bilim, kültür ve çeviri faaliyetlerine önem veren, İslam'ın 'altın çağı' sayılan devlet hangisidir?", options: ["Emeviler", "Abbasiler", "Dört Halife", "Selçuklular"], correctIndex: 1, explanation: "Abbasiler döneminde bilim ve çeviri faaliyetleri zirveye ulaştı; bu dönem İslam'ın altın çağı sayılır." },
  { id: "q_ztar1_3", capsuleId: "ztar1", category: "tarih", question: "Türk-İslam yakınlaşmasını başlatan ve kâğıdın Batı'ya yayılmasını sağlayan savaş hangisidir?", options: ["Malazgirt", "Talas Savaşı", "Bedir", "Kadeş"], correctIndex: 1, explanation: "751 Talas Savaşı'nda Türklerin Abbasiler yanında yer alması Türk-İslam yakınlaşmasını başlattı." },
  { id: "q_ztar1_4", capsuleId: "ztar1", category: "tarih", question: "Hz. Muhammed'in ardından gelen ilk dört halifenin dönemi nasıl adlandırılır?", options: ["Emeviler Dönemi", "Dört Halife (Cumhuriyet) Dönemi", "Abbasiler Dönemi", "Saltanat Dönemi"], correctIndex: 1, explanation: "Hz. Ebubekir, Ömer, Osman ve Ali'nin yönetimi Dört Halife Dönemi olarak adlandırılır." },

  // ztar2 Selçuklu
  { id: "q_ztar2_1", capsuleId: "ztar2", category: "tarih", question: "Anadolu Selçuklu Devleti'nin başkenti neresidir?", options: ["Bursa", "Konya", "İstanbul", "Sivas"], correctIndex: 1, explanation: "Anadolu Selçuklu Devleti'nin başkenti Konya'dır." },
  { id: "q_ztar2_2", capsuleId: "ztar2", category: "tarih", question: "Anadolu'nun kesin olarak Türk yurdu hâline geldiği savaş hangisidir?", options: ["Malazgirt", "Miryokefalon", "Kösedağ", "Pasinler"], correctIndex: 1, explanation: "1176 Miryokefalon Savaşı ile Anadolu kesin olarak Türk yurdu hâline gelmiştir." },
  { id: "q_ztar2_3", capsuleId: "ztar2", category: "tarih", question: "Anadolu Selçuklu Devleti'nin Moğollara yenildiği ve zayıfladığı savaş hangisidir?", options: ["Kösedağ Savaşı", "Malazgirt", "Miryokefalon", "Ankara"], correctIndex: 0, explanation: "1243 Kösedağ Savaşı'nda Moğollara yenilen devlet zayıfladı ve beylikler ortaya çıktı." },
  { id: "q_ztar2_4", capsuleId: "ztar2", category: "tarih", question: "Anadolu Selçukluları ticareti geliştirmek için ne yapmıştır?", options: ["Sadece vergi toplamış", "Kervansaraylar kurup tüccar mallarını güvenceye almış", "Ticareti yasaklamış", "Yalnız tarımla uğraşmış"], correctIndex: 1, explanation: "Kervansaraylar kurdular ve tüccarların zararını devlet güvencesine aldılar (ilk sigorta uygulamalarından)." },

  // ztar3 Beylikler-Osmanlı
  { id: "q_ztar3_1", capsuleId: "ztar3", category: "tarih", question: "Osmanlı Beyliği nerede kurulmuştur?", options: ["Konya çevresinde", "Söğüt-Domaniç çevresinde", "Sivas'ta", "İzmir'de"], correctIndex: 1, explanation: "Osmanlı Beyliği, Bizans sınırındaki Söğüt-Domaniç çevresinde Osman Bey önderliğinde kuruldu." },
  { id: "q_ztar3_2", capsuleId: "ztar3", category: "tarih", question: "Osmanlı'nın hızla büyümesinde etkili olan faktörlerden biri hangisidir?", options: ["Merkezi konumu ve gaza politikası (uç beyliği olması)", "Denizlerden uzaklığı", "Tarımdan uzak durması", "İzole bir bölgede olması"], correctIndex: 0, explanation: "Bizans sınırında (uç bölgede) olması, gaza politikası ve iskân siyaseti Osmanlı'nın hızla büyümesini sağladı." },
  { id: "q_ztar3_3", capsuleId: "ztar3", category: "tarih", question: "Osmanlı'ya donanma ve Rumeli'ye geçiş imkânı sağlayan beylik hangisidir?", options: ["Karamanoğulları", "Karesioğulları", "Germiyanoğulları", "Aydınoğulları"], correctIndex: 1, explanation: "Karesioğulları'nın alınmasıyla Osmanlı donanma ve Rumeli'ye geçiş imkânı elde etti." },
  { id: "q_ztar3_4", capsuleId: "ztar3", category: "tarih", question: "Anadolu beyliklerinin ortaya çıkışının temel nedeni nedir?", options: ["Osmanlı'nın kurulması", "Anadolu Selçuklu'nun Kösedağ sonrası zayıflaması", "Coğrafi keşifler", "Haçlı Seferleri"], correctIndex: 1, explanation: "Anadolu Selçuklu Devleti'nin Kösedağ sonrası zayıflamasıyla Anadolu'da beylikler kuruldu." },

  // ztar4 Dış politika
  { id: "q_ztar4_1", capsuleId: "ztar4", category: "tarih", question: "Atatürk dönemi dış politikasının temel ilkesi nedir?", options: ["Yayılmacılık", "Yurtta sulh, cihanda sulh", "Tarafsızlık", "İzolasyon"], correctIndex: 1, explanation: "Atatürk dönemi dış politikası 'Yurtta sulh, cihanda sulh' ilkesine ve tam bağımsızlığa dayanır." },
  { id: "q_ztar4_2", capsuleId: "ztar4", category: "tarih", question: "Boğazlar üzerindeki Türk egemenliğini pekiştiren 1936 tarihli sözleşme hangisidir?", options: ["Lozan Antlaşması", "Montrö Boğazlar Sözleşmesi", "Sadabat Paktı", "Balkan Antantı"], correctIndex: 1, explanation: "1936 Montrö Boğazlar Sözleşmesi ile Türkiye boğazlar üzerindeki egemenlik haklarını tam olarak geri kazandı." },
  { id: "q_ztar4_3", capsuleId: "ztar4", category: "tarih", question: "Türkiye Milletler Cemiyeti'ne hangi yıl üye olmuştur?", options: ["1923", "1932", "1945", "1952"], correctIndex: 1, explanation: "Türkiye 1932'de Milletler Cemiyeti'ne üye olmuştur." },
  { id: "q_ztar4_4", capsuleId: "ztar4", category: "tarih", question: "Aşağıdakilerden hangisi Atatürk döneminde kurulan bölgesel güvenlik örgütlerindendir?", options: ["NATO", "Balkan Antantı", "Varşova Paktı", "AB"], correctIndex: 1, explanation: "Balkan Antantı (1934) ve Sadabat Paktı (1937) Atatürk döneminde kurulan bölgesel güvenlik örgütleridir." },

  // ztar5 20. yy dünya
  { id: "q_ztar5_1", capsuleId: "ztar5", category: "tarih", question: "I. Dünya Savaşı'nı başlatan (kıvılcım olan) olay nedir?", options: ["Fransız İhtilali", "Saraybosna suikastı", "Sanayi İnkılabı", "Coğrafi keşifler"], correctIndex: 1, explanation: "1914'te Avusturya-Macaristan veliahtının Saraybosna'da öldürülmesi savaşı başlatan kıvılcım oldu." },
  { id: "q_ztar5_2", capsuleId: "ztar5", category: "tarih", question: "20. yüzyıl başında Avrupa devletlerinin hammadde ve pazar için giriştiği yarış nedir?", options: ["Sömürgecilik", "Rönesans", "Reform", "Aydınlanma"], correctIndex: 0, explanation: "Sanayi İnkılabı sonrası hammadde ve pazar ihtiyacı yoğun bir sömürgecilik yarışına yol açtı." },
  { id: "q_ztar5_3", capsuleId: "ztar5", category: "tarih", question: "I. Dünya Savaşı öncesi oluşan bloklardan biri hangisidir?", options: ["NATO", "İtilaf Devletleri", "Varşova Paktı", "AB"], correctIndex: 1, explanation: "Savaş öncesi devletler İttifak (Almanya vd.) ve İtilaf (İngiltere, Fransa, Rusya) bloklarına ayrıldı." },
  { id: "q_ztar5_4", capsuleId: "ztar5", category: "tarih", question: "I. Dünya Savaşı'nın sonuçlarından biri hangisidir?", options: ["İmparatorlukların çöküşü ve haritanın yeniden çizilmesi", "Sömürgeciliğin başlaması", "Matbaanın icadı", "Rönesans'ın doğuşu"], correctIndex: 0, explanation: "Savaş, imparatorlukların (Osmanlı, Avusturya-Macaristan vb.) çöküşüne ve yeni devletlerin doğmasına yol açtı." },

  // zcog1 Coğrafi bölgeler
  { id: "q_zcog1_1", capsuleId: "zcog1", category: "cografya", question: "Türkiye kaç coğrafi bölgeye ayrılmıştır?", options: ["5", "6", "7", "8"], correctIndex: 2, explanation: "Türkiye 1941 Coğrafya Kongresi'nde 7 coğrafi bölgeye ayrılmıştır." },
  { id: "q_zcog1_2", capsuleId: "zcog1", category: "cografya", question: "Türkiye'nin yüz ölçümü en büyük coğrafi bölgesi hangisidir?", options: ["Marmara", "İç Anadolu", "Doğu Anadolu", "Karadeniz"], correctIndex: 2, explanation: "Yüz ölçümü en büyük bölge Doğu Anadolu, en küçük bölge Güneydoğu Anadolu'dur." },
  { id: "q_zcog1_3", capsuleId: "zcog1", category: "cografya", question: "Coğrafi bölge sınırları ile il sınırları için ne söylenebilir?", options: ["Her zaman çakışır", "Her zaman çakışmaz; bir il birden çok bölgede olabilir", "İller bölgelerden büyüktür", "İllerle ilgisizdir"], correctIndex: 1, explanation: "Bölge sınırları il sınırlarıyla çakışmaz; bir il birden fazla coğrafi bölgede yer alabilir." },
  { id: "q_zcog1_4", capsuleId: "zcog1", category: "cografya", question: "Coğrafi bölgeler belirlenirken hangi ölçüt kullanılmamıştır?", options: ["İklim", "Yer şekilleri", "Nüfus ve tarım", "Bölge halkının sevdiği renk"], correctIndex: 3, explanation: "Bölgeler iklim, yer şekilleri, bitki örtüsü, tarım ve nüfus gibi coğrafi ölçütlere göre belirlenmiştir." },

  // zcog2 Topraklar
  { id: "q_zcog2_1", capsuleId: "zcog2", category: "cografya", question: "Akarsuların taşıyıp biriktirdiği en verimli toprak türü hangisidir?", options: ["Laterit", "Alüvyal toprak", "Terra rossa", "Çernozyom"], correctIndex: 1, explanation: "Alüvyal topraklar akarsularca taşınıp ovalarda biriktirilir ve en verimli taşınmış topraklardır." },
  { id: "q_zcog2_2", capsuleId: "zcog2", category: "cografya", question: "Oluştuğu yerde kalan topraklara ne ad verilir?", options: ["Taşınmış toprak", "Yerli toprak", "Alüvyal toprak", "Kumul"], correctIndex: 1, explanation: "Oluştuğu yerde kalan topraklara yerli (zonal/intrazonal) topraklar denir ve iklimle uyumludur." },
  { id: "q_zcog2_3", capsuleId: "zcog2", category: "cografya", question: "Verimli toprağın su ve rüzgârla taşınıp kaybedilmesine ne denir?", options: ["Erozyon", "Süksesyon", "Genleşme", "Buharlaşma"], correctIndex: 0, explanation: "Verimli üst toprağın taşınıp kaybedilmesine erozyon denir; toprağı korumak önemlidir." },
  { id: "q_zcog2_4", capsuleId: "zcog2", category: "cografya", question: "Toprak nasıl oluşur?", options: ["Aniden, bir gecede", "Kayaların uzun sürede ayrışmasıyla", "Suyun donmasıyla", "Bitki ekmekle"], correctIndex: 1, explanation: "Toprak, kayaların fiziksel ve kimyasal ayrışmasıyla çok uzun sürede oluşur." },

  // zcog3 Biyoçeşitlilik
  { id: "q_zcog3_1", capsuleId: "zcog3", category: "cografya", question: "Dünyada biyoçeşitliliğin en zengin olduğu bölgeler nerelerdir?", options: ["Kutuplar", "Çöller", "Ekvator çevresi (yağmur ormanları)", "Yüksek dağlar"], correctIndex: 2, explanation: "Sıcak ve nemli Ekvator çevresi (yağmur ormanları) biyoçeşitliliğin en zengin olduğu bölgelerdir." },
  { id: "q_zcog3_2", capsuleId: "zcog3", category: "cografya", question: "Türkiye'nin biyoçeşitlilik açısından zengin olmasının nedeni nedir?", options: ["Küçük olması", "Üç farklı iklim/flora bölgesinin kesişiminde olması", "Denizden uzak olması", "Düz bir arazi olması"], correctIndex: 1, explanation: "Türkiye üç farklı flora bölgesinin kesişiminde ve engebeli bir arazide olduğu için biyoçeşitliliği çok zengindir." },
  { id: "q_zcog3_3", capsuleId: "zcog3", category: "cografya", question: "Aşağıdakilerden hangisi biyoçeşitliliği azaltan bir tehdittir?", options: ["Habitat tahribi", "Yağış", "Güneş ışığı", "Toprak oluşumu"], correctIndex: 0, explanation: "Habitat tahribi, kirlilik ve aşırı avlanma gibi insan faaliyetleri biyoçeşitliliği azaltır." },
  { id: "q_zcog3_4", capsuleId: "zcog3", category: "cografya", question: "Biyoçeşitlilik neyi ifade eder?", options: ["Yalnızca hayvan sayısını", "Canlı türlerinin ve genetik çeşitliliğin zenginliğini", "Toprak miktarını", "Su miktarını"], correctIndex: 1, explanation: "Biyoçeşitlilik, bir bölgedeki canlı türlerinin ve genetik çeşitliliğin zenginliğidir." },

  // zcog4 Örgütler
  { id: "q_zcog4_1", capsuleId: "zcog4", category: "cografya", question: "Dünya barışı ve genel iş birliği için kurulan örgüt hangisidir?", options: ["NATO", "Birleşmiş Milletler (BM)", "OPEC", "IMF"], correctIndex: 1, explanation: "Birleşmiş Milletler (BM), dünya barışı ve uluslararası iş birliği için kurulan genel/siyasi örgüttür." },
  { id: "q_zcog4_2", capsuleId: "zcog4", category: "cografya", question: "Türkiye'nin 1952'de üye olduğu askerî örgüt hangisidir?", options: ["Varşova Paktı", "NATO", "AB", "OPEC"], correctIndex: 1, explanation: "Türkiye 1952'de askerî savunma ittifakı olan NATO'ya üye olmuştur." },
  { id: "q_zcog4_3", capsuleId: "zcog4", category: "cografya", question: "Petrol ihraç eden ülkelerin oluşturduğu ekonomik örgüt hangisidir?", options: ["OPEC", "NATO", "BM", "UNESCO"], correctIndex: 0, explanation: "OPEC, petrol ihraç eden ülkelerin oluşturduğu ekonomik bir örgüttür." },
  { id: "q_zcog4_4", capsuleId: "zcog4", category: "cografya", question: "Türkiye'yi jeopolitik olarak önemli kılan başlıca özellik nedir?", options: ["Küçük olması", "Asya-Avrupa köprüsü ve enerji koridoru konumu", "Denizden uzak olması", "Nüfusunun az olması"], correctIndex: 1, explanation: "Asya ile Avrupa arasında köprü olması, boğazları kontrol etmesi ve enerji koridoru konumu Türkiye'yi jeopolitik açıdan önemli kılar." },

  // zede1 Masal-fabl
  { id: "q_zede1_1", capsuleId: "zede1", category: "edebiyat", question: "Kahramanları çoğunlukla hayvanlar olan, sonunda ahlak dersi veren kısa öykü türü hangisidir?", options: ["Masal", "Fabl", "Destan", "Roman"], correctIndex: 1, explanation: "Fabl, kişileştirilmiş hayvanların yer aldığı, sonunda ders (kıssadan hisse) veren kısa öyküdür." },
  { id: "q_zede1_2", capsuleId: "zede1", category: "edebiyat", question: "Fabl türünün dünyaca ünlü ustalarından biri kimdir?", options: ["La Fontaine", "Shakespeare", "Tolstoy", "Homeros"], correctIndex: 0, explanation: "La Fontaine ve Ezop, fabl türünün en ünlü ustalarıdır." },
  { id: "q_zede1_3", capsuleId: "zede1", category: "edebiyat", question: "Masalın belirgin özelliği hangisidir?", options: ["Gerçek olaylar anlatır", "Olağanüstü olaylar içerir, belirli zaman-mekân yoktur", "Belgelere dayanır", "Yalnız hayvanları anlatır"], correctIndex: 1, explanation: "Masal, olağanüstü olayları belirli bir zaman-mekân belirtmeden anlatan anonim türdür." },
  { id: "q_zede1_4", capsuleId: "zede1", category: "edebiyat", question: "Fablda hayvanlar aslında neyi temsil eder?", options: ["Gerçek hayvanları", "İnsan tiplerini ve davranışlarını", "Bitkileri", "Mevsimleri"], correctIndex: 1, explanation: "Fabldaki hayvanlar insan tiplerini simgeler (tilki kurnazlık, karınca çalışkanlık); insan eleştirisi yapılır." },

  // zede2 Destan
  { id: "q_zede2_1", capsuleId: "zede2", category: "edebiyat", question: "Söyleyeni belli olmayan, halkın ortak ürünü olan destan türü hangisidir?", options: ["Doğal (anonim) destan", "Yapma destan", "Modern destan", "Kişisel destan"], correctIndex: 0, explanation: "Doğal (anonim) destanlar halkın ortak malıdır ve söyleyeni belli değildir (Oğuz Kağan, İlyada)." },
  { id: "q_zede2_2", capsuleId: "zede2", category: "edebiyat", question: "Aşağıdakilerden hangisi bir Türk destanıdır?", options: ["İlyada", "Şehname", "Ergenekon", "Odysseia"], correctIndex: 2, explanation: "Ergenekon Destanı bir Türk destanıdır; İlyada-Odysseia Yunan, Şehname İran destanıdır." },
  { id: "q_zede2_3", capsuleId: "zede2", category: "edebiyat", question: "Belirli bir şairin destan geleneğini örnek alarak yazdığı destana ne denir?", options: ["Doğal destan", "Yapma (suni) destan", "Anonim destan", "Halk destanı"], correctIndex: 1, explanation: "Bir şairin yazdığı destana yapma (suni) destan denir; Tevfik Fikret'in 'Sis'i örnektir." },
  { id: "q_zede2_4", capsuleId: "zede2", category: "edebiyat", question: "Dünyanın bilinen en uzun destanı hangisidir?", options: ["Oğuz Kağan", "Manas Destanı", "İlyada", "Ergenekon"], correctIndex: 1, explanation: "Kırgız Türklerine ait Manas Destanı, dünyanın bilinen en uzun destanıdır." },

  // zede3 Anonim halk şiiri
  { id: "q_zede3_1", capsuleId: "zede3", category: "edebiyat", question: "Genellikle 7'li hece ölçüsüyle, tek dörtlükten oluşan anonim halk şiiri türü hangisidir?", options: ["Türkü", "Mani", "Koşma", "Gazel"], correctIndex: 1, explanation: "Mani, 7'li hece ölçüsüyle söylenen, tek dörtlükten oluşan anonim halk şiiri türüdür." },
  { id: "q_zede3_2", capsuleId: "zede3", category: "edebiyat", question: "Bir ölüm veya acı olay üzerine yakılan anonim halk şiiri hangisidir?", options: ["Ağıt", "Mani", "Ninni", "Türkü"], correctIndex: 0, explanation: "Ağıt, ölüm veya acı bir olay üzerine yakılan şiirdir; İslamiyet öncesindeki 'sagu'nun karşılığıdır." },
  { id: "q_zede3_3", capsuleId: "zede3", category: "edebiyat", question: "Ezgiyle söylenen, bent ve nakarattan (bağlantı) oluşan anonim ürün hangisidir?", options: ["Mani", "Türkü", "Gazel", "Kaside"], correctIndex: 1, explanation: "Türkü, ezgiyle söylenen, bent ve nakarat bölümlerinden oluşan anonim halk şiiridir." },
  { id: "q_zede3_4", capsuleId: "zede3", category: "edebiyat", question: "Maninin ilk iki dizesi genellikle nasıl bir işlev taşır?", options: ["Asıl mesajı verir", "Uyağı hazırlayan doldurma dizelerdir", "Sonucu bildirir", "Kişileri tanıtır"], correctIndex: 1, explanation: "Maninin ilk iki dizesi çoğu zaman uyağı hazırlayan 'doldurma' dizelerdir; asıl duygu son iki dizededir." },

  // zede4 Söylev
  { id: "q_zede4_1", capsuleId: "zede4", category: "edebiyat", question: "Bir topluluğu etkilemek için coşkulu ve etkili biçimde yapılan konuşmaya ne denir?", options: ["Deneme", "Söylev (nutuk)", "Makale", "Fıkra"], correctIndex: 1, explanation: "Bir topluluğu etkilemeyi amaçlayan etkili konuşma türüne söylev (hitabet/nutuk) denir." },
  { id: "q_zede4_2", capsuleId: "zede4", category: "edebiyat", question: "Türk edebiyatının en önemli söylev örneği hangisidir?", options: ["Aşk-ı Memnu", "Nutuk (Atatürk)", "Çalıkuşu", "Sinekli Bakkal"], correctIndex: 1, explanation: "Atatürk'ün 'Nutuk'u, Türk edebiyatının en önemli söylev örneği ve tarihsel belgesidir." },
  { id: "q_zede4_3", capsuleId: "zede4", category: "edebiyat", question: "Bir kişiyle yapılan soru-cevap görüşmesinin yazıya geçirilmiş türü hangisidir?", options: ["Mülakat (röportaj)", "Deneme", "Söylev", "Masal"], correctIndex: 0, explanation: "Bir kişiyle yapılan soru-cevap temelli görüşmenin yazılı hâli mülakat (röportaj)tır." },
  { id: "q_zede4_4", capsuleId: "zede4", category: "edebiyat", question: "Söylev türünün başarılı olması için hangi özellik gereklidir?", options: ["Kapalı ve karmaşık dil", "Açık, akıcı ve inandırıcı bir dil", "Yalnız sayısal veri", "Şiirsel ölçü"], correctIndex: 1, explanation: "Söylev; dinleyiciyi etkilemek için açık, akıcı, coşkulu ve inandırıcı bir dil gerektirir." },

  // zfel1 Psikoloji
  { id: "q_zfel1_1", capsuleId: "zfel1", category: "felsefe", question: "Psikoloji neyi bilimsel olarak inceler?", options: ["Yalnızca hastalıkları", "Davranışları ve zihinsel süreçleri", "Toplumsal olguları", "Tarihsel olayları"], correctIndex: 1, explanation: "Psikoloji, davranışları ve zihinsel süreçleri (algı, bellek, öğrenme, duygu) bilimsel yöntemlerle inceler." },
  { id: "q_zfel1_2", capsuleId: "zfel1", category: "felsefe", question: "Yalnızca gözlenebilir davranışı inceleyen psikoloji yaklaşımı hangisidir?", options: ["Psikanaliz", "Davranışçılık", "Hümanist yaklaşım", "Bilişsel yaklaşım"], correctIndex: 1, explanation: "Davranışçılık (Watson, Skinner) yalnızca gözlenebilen davranışları inceler." },
  { id: "q_zfel1_3", capsuleId: "zfel1", category: "felsefe", question: "Bilinçaltını merkeze alan, Freud'un kurduğu yaklaşım hangisidir?", options: ["Davranışçılık", "Psikanaliz", "Bilişsel", "Hümanist"], correctIndex: 1, explanation: "Psikanaliz, Sigmund Freud tarafından kurulmuş ve bilinçaltını merkeze almıştır." },
  { id: "q_zfel1_4", capsuleId: "zfel1", category: "felsefe", question: "Maslow'un ihtiyaçlar hiyerarşisinde en tepede hangi ihtiyaç vardır?", options: ["Fizyolojik ihtiyaçlar", "Güvenlik", "Kendini gerçekleştirme", "Ait olma"], correctIndex: 2, explanation: "Maslow'un piramidinin en tepesinde 'kendini gerçekleştirme' (potansiyelini tam kullanma) yer alır." },

  // zfel2 Sosyoloji
  { id: "q_zfel2_1", capsuleId: "zfel2", category: "felsefe", question: "Sosyoloji neyi inceler?", options: ["Bireyin ruhsal yapısını", "Toplumu ve toplumsal olguları", "Doğa olaylarını", "Sayıları"], correctIndex: 1, explanation: "Sosyoloji; toplumu, toplumsal grupları, kurumları ve toplumsal olayları bilimsel olarak inceler." },
  { id: "q_zfel2_2", capsuleId: "zfel2", category: "felsefe", question: "Aşağıdakilerden hangisi bir sosyoloji sorusudur?", options: ["Ahmet neden mutsuz?", "Ülkedeki işsizlik neden arttı?", "Bu ilaç nasıl etki eder?", "Su kaç derecede kaynar?"], correctIndex: 1, explanation: "Sosyoloji tekil olayları değil, toplumsal olguları inceler; 'işsizliğin artışı' toplumsal bir olgudur." },
  { id: "q_zfel2_3", capsuleId: "zfel2", category: "felsefe", question: "'Sosyoloji' terimini kullanan düşünür kimdir?", options: ["Auguste Comte", "Platon", "Freud", "Newton"], correctIndex: 0, explanation: "'Sosyoloji' terimini Auguste Comte kullanmış; İbn Haldun ise öncüsü kabul edilir." },
  { id: "q_zfel2_4", capsuleId: "zfel2", category: "felsefe", question: "Sosyolojinin bilimsel olabilmesi için nasıl olması gerekir?", options: ["Değer yargısı içermeli", "Nesnel ve değer yargısından uzak olmalı", "Kişisel görüş bildirmeli", "Olması gerekeni anlatmalı"], correctIndex: 1, explanation: "Sosyoloji, olanı inceler; nesnel ve değer yargısından uzak olmalıdır." },

  // zfel3 İslam felsefesi
  { id: "q_zfel3_1", capsuleId: "zfel3", category: "felsefe", question: "'Muallim-i Sani' (İkinci Öğretmen) olarak anılan İslam filozofu kimdir?", options: ["İbn Sina", "Farabi", "Gazali", "İbn Rüşd"], correctIndex: 1, explanation: "Farabi, akıl ve mantığa verdiği önemle 'Muallim-i Sani' (İkinci Öğretmen) olarak anılır." },
  { id: "q_zfel3_2", capsuleId: "zfel3", category: "felsefe", question: "Hem filozof hem hekim olan, 'El-Kanun fi't-Tıb' eserini yazan düşünür kimdir?", options: ["Farabi", "İbn Sina (Avicenna)", "Gazali", "Kindî"], correctIndex: 1, explanation: "İbn Sina hem filozof hem hekimdir; tıp eseri 'El-Kanun fi't-Tıb' yüzyıllarca kaynak olmuştur." },
  { id: "q_zfel3_3", capsuleId: "zfel3", category: "felsefe", question: "Aşırı akılcılığa eleştiri getirip tasavvufu güçlendiren İslam düşünürü kimdir?", options: ["Farabi", "İbn Sina", "Gazali", "İbn Haldun"], correctIndex: 2, explanation: "Gazali, 'Filozofların Tutarsızlığı' eseriyle felsefeye eleştiri getirmiş ve tasavvufu güçlendirmiştir." },
  { id: "q_zfel3_4", capsuleId: "zfel3", category: "felsefe", question: "İslam felsefesi hangi antik geleneği İslam düşüncesiyle birleştirmiştir?", options: ["Antik Yunan felsefesi", "Mısır mitolojisi", "Çin felsefesi", "Hint dini"], correctIndex: 0, explanation: "İslam felsefesi, antik Yunan felsefesini (özellikle Aristoteles ve Platon) İslam düşüncesiyle birleştirmiştir." },
];
