import type { Question } from "./data";

// extraCapsules4 (YKS çıkmış soru temelli konular) için kaliteli sorular — her konu 4 soru
export const questionsExtra9: Question[] = [
  // yt1 Paragrafta anlam bütünlüğü
  { id: "q_yt1_1", capsuleId: "yt1", category: "turkce", question: "Bir paragrafa yerleştirilecek cümle 'Oysa bu görüş kısa sürede çürütüldü.' biçimindedir. Bu cümle kendinden önceki cümleyle nasıl bir ilişki kurar?", options: ["Onu örneklendirir", "Onunla zıtlık/karşıtlık kurar", "Onu tanımlar", "Onu sonuca bağlar"], correctIndex: 1, explanation: "'Oysa' bir karşıtlık bağlacıdır; cümle, kendinden önce sunulan bir görüşe zıt bir yargı getirir. Doğru yer, bir görüşün öne sürüldüğü cümleden hemen sonrasıdır." },
  { id: "q_yt1_2", capsuleId: "yt1", category: "turkce", question: "'Akışı bozan cümle' sorularında hangi cümle işaretlenir?", options: ["En uzun cümle", "Paragrafın konusundan sapan cümle", "Soru içeren cümle", "İlk cümle"], correctIndex: 1, explanation: "Anlam akışını bozan cümle, paragrafın ana konusundan uzaklaşıp farklı bir düşünceye geçen cümledir." },
  { id: "q_yt1_3", capsuleId: "yt1", category: "turkce", question: "Cümle yerleştirme sorularında hangi ipuçları takip edilmelidir?", options: ["Yalnızca cümlenin uzunluğu", "Zamir, bağlaç ve ortak sözcük gibi anlam köprüleri", "Noktalama işaretleri sayısı", "Sözcük sayısı"], correctIndex: 1, explanation: "'Bu, o, ancak, ayrıca' gibi bağlayıcılar ve ortak sözcükler cümleler arası bağı gösterir; yerleştirme bu köprülere göre yapılır." },
  { id: "q_yt1_4", capsuleId: "yt1", category: "turkce", question: "Paragrafı iki bölüme ayırma sorularında ayrım noktası nasıl belirlenir?", options: ["Konunun/bakış açısının değiştiği yer", "En kısa cümlenin bulunduğu yer", "İlk virgülün yeri", "Son cümle"], correctIndex: 0, explanation: "Paragrafı ikiye bölme sorusunda, konunun ya da bakış açısının değiştiği nokta ayrım yeridir." },

  // yt2 Fiilimsiler
  { id: "q_yt2_1", capsuleId: "yt2", category: "turkce", question: "'Koşarak gelen çocuk, gülmeyi çok severdi.' cümlesinde sırasıyla hangi fiilimsiler vardır?", options: ["Zarf-fiil, sıfat-fiil, isim-fiil", "İsim-fiil, zarf-fiil, sıfat-fiil", "Sıfat-fiil, isim-fiil, zarf-fiil", "Zarf-fiil, isim-fiil, sıfat-fiil"], correctIndex: 0, explanation: "'Koşarak' zarf-fiil (-arak), 'gelen' sıfat-fiil (-en, ismi niteler), 'gülmeyi' isim-fiildir (-me)." },
  { id: "q_yt2_2", capsuleId: "yt2", category: "turkce", question: "Aşağıdaki cümlelerin hangisinde fiilimsi YOKTUR?", options: ["Yürüyerek eve gitti.", "Gelen kişiyi tanımadım.", "Çocuk bahçede topunu attı.", "Okumak beni dinlendirir."], correctIndex: 2, explanation: "'Çocuk bahçede topunu attı.' tek yüklemli basit cümledir, fiilimsi içermez. Diğerlerinde -erek, -en, -mak fiilimsileri vardır." },
  { id: "q_yt2_3", capsuleId: "yt2", category: "turkce", question: "'-an, -ası, -mez, -dik, -ecek, -miş' ekleriyle yapılan fiilimsi türü hangisidir?", options: ["İsim-fiil", "Sıfat-fiil", "Zarf-fiil", "Ek-fiil"], correctIndex: 1, explanation: "Bu ekler bir ismi niteleyen sıfat-fiil (ortaç) eklerdir: 'gelecek yıl', 'tanıdık yüz'." },
  { id: "q_yt2_4", capsuleId: "yt2", category: "turkce", question: "Fiilimsi bulunan bir cümlenin yapısı için ne söylenebilir?", options: ["Kesinlikle basit cümledir", "En az iki yüklem taşır, basit cümle değildir", "Her zaman devrik cümledir", "Yüklemi isimdir"], correctIndex: 1, explanation: "Fiilimsi ikinci bir yargı oluşturduğundan cümle en az iki yüklem taşır; bu yüzden basit cümle olamaz (girişik birleşik cümledir)." },

  // yt3 Cümlede anlam ilişkileri
  { id: "q_yt3_1", capsuleId: "yt3", category: "turkce", question: "'Ali de kardeşi kadar çalışkandır.' cümlesinde hangi anlam ilişkisi vardır?", options: ["Üstünlük bildiren karşılaştırma", "Eşitlik bildiren karşılaştırma", "Koşul", "Neden-sonuç"], correctIndex: 1, explanation: "'kadar' edatı burada iki kişiyi eşit düzeyde kıyaslar; üstünlük değil, eşitlik bildiren bir karşılaştırmadır." },
  { id: "q_yt3_2", capsuleId: "yt3", category: "turkce", question: "'Düzenli çalışırsan bu sınavı kazanırsın.' cümlesindeki anlam ilişkisi nedir?", options: ["Koşul (şart)", "Tanımlama", "Karşılaştırma", "Öneri"], correctIndex: 0, explanation: "'-sa/-se' ekiyle kurulan bu cümlede bir eylem, başka bir eylemin koşuludur (şart-sonuç)." },
  { id: "q_yt3_3", capsuleId: "yt3", category: "turkce", question: "'Roman, olayları geniş bir zamana yayarak anlatan edebî türdür.' cümlesi hangi anlam ilişkisini taşır?", options: ["Öneri", "Tanımlama", "Koşul", "Olasılık"], correctIndex: 1, explanation: "Cümle 'roman nedir?' sorusuna yanıt verip türün ne olduğunu açıkladığı için tanımlama cümlesidir." },
  { id: "q_yt3_4", capsuleId: "yt3", category: "turkce", question: "Aşağıdaki cümlelerin hangisinde öneri anlamı vardır?", options: ["Yarın hava yağmurlu olacak.", "Bu kitabı mutlaka okumalısın.", "Sınav çok zordu.", "Kardeşi ondan uzundur."], correctIndex: 1, explanation: "'-malı/-meli' gereklilik eki burada yol gösterici bir öneri anlamı katmaktadır." },

  // ym1 Kesir ve yüzde
  { id: "q_ym1_1", capsuleId: "ym1", category: "matematik", question: "Bir işçi bir işin önce 1/3'ünü, kalanın yarısını yapıyor. İşin ne kadarı kalmıştır?", options: ["1/2", "1/3", "1/6", "2/3"], correctIndex: 1, explanation: "Önce 1/3 yapıldı, kalan 2/3. Kalanın yarısı: (2/3)·(1/2)=1/3 daha yapıldı. Toplam yapılan 1/3+1/3=2/3; kalan 1/3'tür." },
  { id: "q_ym1_2", capsuleId: "ym1", category: "matematik", question: "Bir ürünün fiyatı önce %20 artırılıp sonra %20 azaltılıyor. Son fiyat ilk fiyatın yüzde kaçıdır?", options: ["%100", "%96", "%104", "%92"], correctIndex: 1, explanation: "1,20 × 0,80 = 0,96 olduğundan son fiyat ilk fiyatın %96'sıdır (yani %4 azalır). Yüzde değişimler doğrudan toplanmaz." },
  { id: "q_ym1_3", capsuleId: "ym1", category: "matematik", question: "Bir sayının %40'ı 60 ise bu sayı kaçtır?", options: ["100", "120", "150", "24"], correctIndex: 2, explanation: "Sayı x olsun: 0,40·x = 60 → x = 60/0,40 = 150." },
  { id: "q_ym1_4", capsuleId: "ym1", category: "matematik", question: "Kesir/yüzde problemlerinde 'kalanın' ifadesi neden kritiktir?", options: ["Bütün üzerinden işlem yapılmasını sağlar", "İşlemin baştaki bütün üzerinden değil, o anki kalan üzerinden yapılacağını gösterir", "Sonucu ikiye böler", "Yüzdeyi kesire çevirir"], correctIndex: 1, explanation: "'Kalanın' ifadesi, o adımdaki işlemin başlangıçtaki bütün üzerinden değil, o ana kadar geriye kalan miktar üzerinden yapılacağını belirtir; en sık yapılan hata budur." },

  // ym2 Fonksiyon grafiği
  { id: "q_ym2_1", capsuleId: "ym2", category: "matematik", question: "Bir f fonksiyonunun grafiği x eksenini -2 ve 3 noktalarında kesiyorsa bu noktalar neyi ifade eder?", options: ["Fonksiyonun maksimumları", "Fonksiyonun kökleri (f(x)=0)", "Fonksiyonun tanımsız olduğu yerler", "Eğimin sıfır olduğu yerler"], correctIndex: 1, explanation: "Grafiğin x eksenini kestiği noktalar f(x)=0 denklemini sağlar; bunlar fonksiyonun kökleridir." },
  { id: "q_ym2_2", capsuleId: "ym2", category: "matematik", question: "Bir fonksiyonun grafiği bir aralıkta soldan sağa yükseliyorsa o aralıkta fonksiyon nasıldır?", options: ["Azalandır", "Artandır", "Sabittir", "Tanımsızdır"], correctIndex: 1, explanation: "Grafik yükseliyorsa fonksiyon artandır (bu aralıkta türev pozitiftir)." },
  { id: "q_ym2_3", capsuleId: "ym2", category: "matematik", question: "f(x) grafiği x ekseninin altında kaldığı aralıkta fonksiyonun işareti nasıldır?", options: ["Pozitif", "Negatif", "Sıfır", "Belirsiz"], correctIndex: 1, explanation: "Grafik x ekseninin altındaysa f(x) değerleri negatiftir." },
  { id: "q_ym2_4", capsuleId: "ym2", category: "matematik", question: "y=f(x) ve y=g(x) grafiklerinin kesim noktaları neyi verir?", options: ["f(x)·g(x)=0 çözümlerini", "f(x)=g(x) denkleminin çözümlerini", "f(x)+g(x)=0 çözümlerini", "Türevlerin eşit olduğu noktaları"], correctIndex: 1, explanation: "İki grafiğin kesim noktalarında y değerleri eşittir, yani f(x)=g(x) denklemi sağlanır." },

  // ym3 Mutlak değer
  { id: "q_ym3_1", capsuleId: "ym3", category: "matematik", question: "|x - 2| = 5 denkleminin çözümleri nelerdir?", options: ["x=7 veya x=-3", "x=5 veya x=-5", "x=3 veya x=7", "x=2 veya x=5"], correctIndex: 0, explanation: "x-2=5 → x=7 veya x-2=-5 → x=-3. İki çözüm: 7 ve -3." },
  { id: "q_ym3_2", capsuleId: "ym3", category: "matematik", question: "|x| < 4 eşitsizliğinin çözüm kümesi nedir?", options: ["x > 4", "x < -4", "-4 < x < 4", "x < -4 veya x > 4"], correctIndex: 2, explanation: "|x| < a ise -a < x < a olur; burada -4 < x < 4." },
  { id: "q_ym3_3", capsuleId: "ym3", category: "matematik", question: "|x| = -3 denkleminin çözümü hakkında ne söylenir?", options: ["x=3", "x=-3", "Çözüm yoktur", "x=0"], correctIndex: 2, explanation: "Mutlak değer negatif olamayacağından |x|=-3 denkleminin çözümü yoktur." },
  { id: "q_ym3_4", capsuleId: "ym3", category: "matematik", question: "|x| > 2 eşitsizliğinin çözümü hangisidir?", options: ["-2 < x < 2", "x < -2 veya x > 2", "x = 2", "0 < x < 2"], correctIndex: 1, explanation: "|x| > a ise x < -a veya x > a olur; burada x < -2 veya x > 2." },

  // yg1 Benzerlik-Thales
  { id: "q_yg1_1", capsuleId: "yg1", category: "geometri", question: "Bir üçgende bir kenara paralel çizilen doğru diğer iki kenarı nasıl böler?", options: ["Eşit iki parçaya", "Aynı oranda (orantılı)", "Dik olarak", "Rastgele"], correctIndex: 1, explanation: "Temel Orantı Teoremi (Thales): bir kenara paralel doğru, diğer iki kenarı aynı oranda böler." },
  { id: "q_yg1_2", capsuleId: "yg1", category: "geometri", question: "Benzerlik oranı 3 olan iki üçgenin alanları oranı kaçtır?", options: ["3", "6", "9", "27"], correctIndex: 2, explanation: "Alan oranı, benzerlik oranının karesidir: 3² = 9." },
  { id: "q_yg1_3", capsuleId: "yg1", category: "geometri", question: "İki üçgenin benzer olması için yeterli koşullardan biri hangisidir?", options: ["İki açısının eşit olması (AA)", "Bir kenarının eşit olması", "Çevrelerinin eşit olması", "Bir açısının 90° olması"], correctIndex: 0, explanation: "İki açısı eşit olan üçgenler benzerdir (AA benzerlik kuralı); üçüncü açı da otomatik eşit olur." },
  { id: "q_yg1_4", capsuleId: "yg1", category: "geometri", question: "Benzer iki üçgende kenar oranı 2 ise çevre oranı kaçtır?", options: ["2", "4", "8", "1"], correctIndex: 0, explanation: "Çevre oranı kenar oranına eşittir (k); alan oranı ise karesidir (k²). Kenar oranı 2 ise çevre oranı da 2'dir." },

  // yg2 Çemberde açı
  { id: "q_yg2_1", capsuleId: "yg2", category: "geometri", question: "Bir çemberde çapı gören çevre açının ölçüsü kaç derecedir?", options: ["45°", "60°", "90°", "180°"], correctIndex: 2, explanation: "Thales teoremine göre çapı gören çevre açı daima 90°'dir." },
  { id: "q_yg2_2", capsuleId: "yg2", category: "geometri", question: "Bir yayı gören merkez açı 100° ise aynı yayı gören çevre açı kaç derecedir?", options: ["50°", "100°", "200°", "25°"], correctIndex: 0, explanation: "Çevre açı, gördüğü yayın (ve merkez açının) yarısıdır: 100/2 = 50°." },
  { id: "q_yg2_3", capsuleId: "yg2", category: "geometri", question: "Kirişler dörtgeninde karşılıklı iki iç açının toplamı kaç derecedir?", options: ["90°", "180°", "270°", "360°"], correctIndex: 1, explanation: "Çembersel (kirişler) dörtgende karşılıklı açıların toplamı 180°'dir." },
  { id: "q_yg2_4", capsuleId: "yg2", category: "geometri", question: "Aynı yayı gören iki farklı çevre açı için ne söylenir?", options: ["Toplamları 90°'dir", "Birbirine eşittir", "Biri diğerinin iki katıdır", "Toplamları 180°'dir"], correctIndex: 1, explanation: "Aynı yayı gören tüm çevre açılar birbirine eşittir; hepsi o yayın yarısı kadardır." },

  // yf1 Hareket grafikleri
  { id: "q_yf1_1", capsuleId: "yf1", category: "fizik", question: "Konum-zaman grafiğinin eğimi neyi verir?", options: ["İvmeyi", "Hızı", "Yolu", "Kuvveti"], correctIndex: 1, explanation: "Konum-zaman grafiğinin eğimi hızı verir (konumun zamana göre değişimi)." },
  { id: "q_yf1_2", capsuleId: "yf1", category: "fizik", question: "Hız-zaman grafiğinin altında kalan alan neyi verir?", options: ["İvmeyi", "Alınan yolu", "Kütleyi", "Gücü"], correctIndex: 1, explanation: "Hız-zaman grafiğinin altındaki alan, alınan yolu (yer değiştirmeyi) verir." },
  { id: "q_yf1_3", capsuleId: "yf1", category: "fizik", question: "Hız-zaman grafiğinin eğimi neyi ifade eder?", options: ["Yolu", "İvmeyi", "Konumu", "Enerjiyi"], correctIndex: 1, explanation: "Hız-zaman grafiğinin eğimi ivmeyi verir (hızın zamana göre değişimi)." },
  { id: "q_yf1_4", capsuleId: "yf1", category: "fizik", question: "Sabit hızla giden bir cismin hız-zaman grafiği nasıldır?", options: ["Eğimli bir doğru", "Zaman eksenine paralel yatay bir doğru", "Parabol", "Dikey doğru"], correctIndex: 1, explanation: "Hız değişmediği için hız-zaman grafiği yatay (zaman eksenine paralel) bir doğrudur; ivme sıfırdır." },

  // yf2 Kaldırma kuvveti
  { id: "q_yf2_1", capsuleId: "yf2", category: "fizik", question: "Yoğunluğu sıvının yoğunluğundan küçük olan bir cisim sıvıya bırakılırsa ne olur?", options: ["Dibe batar", "Askıda kalır", "Bir kısmı dışarıda kalacak şekilde yüzer", "Erir"], correctIndex: 2, explanation: "Cisim yoğunluğu sıvıdan küçükse yüzer; bir kısmı sıvı yüzeyinin üstünde kalır." },
  { id: "q_yf2_2", capsuleId: "yf2", category: "fizik", question: "Kaldırma kuvveti hangi büyüklüklere bağlıdır?", options: ["Cismin rengine ve şekline", "Batan hacim, sıvı yoğunluğu ve yer çekimine", "Cismin sıcaklığına", "Yalnız cismin kütlesine"], correctIndex: 1, explanation: "F = V_batan · d_sıvı · g olduğundan kaldırma kuvveti batan hacme, sıvı yoğunluğuna ve g'ye bağlıdır." },
  { id: "q_yf2_3", capsuleId: "yf2", category: "fizik", question: "Bir sıvıda askıda kalan (her derinlikte duran) cisim için ne söylenir?", options: ["Yoğunluğu sıvıdan büyüktür", "Yoğunluğu sıvıya eşittir", "Yoğunluğu sıvıdan küçüktür", "Kütlesi sıfırdır"], correctIndex: 1, explanation: "Cisim askıda kalıyorsa yoğunluğu sıvının yoğunluğuna eşittir; kaldırma kuvveti ağırlığa eşittir." },
  { id: "q_yf2_4", capsuleId: "yf2", category: "fizik", question: "Yüzen bir cismin batan hacim oranı neye eşittir?", options: ["Sıvı yoğunluğu / cisim yoğunluğu", "Cisim yoğunluğu / sıvı yoğunluğu", "Cismin ağırlığı", "1"], correctIndex: 1, explanation: "Yüzen cisimde batan hacim oranı = cisim yoğunluğu / sıvı yoğunluğudur; bu yüzden buzdağının çok azı görünür." },

  // yk1 Mol-stokiyometri
  { id: "q_yk1_1", capsuleId: "yk1", category: "kimya", question: "44 gram CO₂'de kaç mol bulunur? (C=12, O=16)", options: ["0,5 mol", "1 mol", "2 mol", "44 mol"], correctIndex: 1, explanation: "CO₂ mol kütlesi = 12 + 2·16 = 44 g/mol. n = m/M = 44/44 = 1 mol." },
  { id: "q_yk1_2", capsuleId: "yk1", category: "kimya", question: "Normal koşullarda 2 mol gazın hacmi kaç litredir?", options: ["11,2 L", "22,4 L", "44,8 L", "67,2 L"], correctIndex: 2, explanation: "NK'da 1 mol gaz 22,4 L'dir; 2 mol → 2·22,4 = 44,8 L." },
  { id: "q_yk1_3", capsuleId: "yk1", category: "kimya", question: "İki reaktifin verildiği bir tepkimede ürün miktarını hangi madde belirler?", options: ["Fazla olan madde", "Sınırlayıcı (önce tükenen) bileşen", "Mol kütlesi büyük olan", "Katı olan madde"], correctIndex: 1, explanation: "Ürün miktarını önce tükenen (sınırlayıcı) bileşen belirler; fazla olan madde artar." },
  { id: "q_yk1_4", capsuleId: "yk1", category: "kimya", question: "Bir tepkimenin verimi nasıl hesaplanır?", options: ["(teorik ürün / gerçek ürün) × 100", "(gerçek ürün / teorik ürün) × 100", "gerçek ürün × teorik ürün", "gerçek ürün + teorik ürün"], correctIndex: 1, explanation: "Verim (%) = (gerçekte elde edilen ürün / teorik olarak beklenen ürün) × 100." },

  // yk2 Periyodik sistem
  { id: "q_yk2_1", capsuleId: "yk2", category: "kimya", question: "Periyodik cetvelde soldan sağa gidildikçe atom yarıçapı nasıl değişir?", options: ["Artar", "Azalır", "Değişmez", "Önce artar sonra azalır"], correctIndex: 1, explanation: "Soldan sağa çekirdek yükü artar, elektronlar daha güçlü çekilir; atom yarıçapı azalır." },
  { id: "q_yk2_2", capsuleId: "yk2", category: "kimya", question: "En yüksek elektronegatifliğe sahip element hangisidir?", options: ["Sodyum (Na)", "Flor (F)", "Sezyum (Cs)", "Demir (Fe)"], correctIndex: 1, explanation: "Elektronegatiflik sağ üste doğru artar; en yüksek değer flordadır (F)." },
  { id: "q_yk2_3", capsuleId: "yk2", category: "kimya", question: "Bir grupta yukarıdan aşağıya inildikçe iyonlaşma enerjisi nasıl değişir?", options: ["Artar", "Azalır", "Değişmez", "İki katına çıkar"], correctIndex: 1, explanation: "Aşağı inildikçe atom yarıçapı büyür, dış elektron daha zayıf tutulur; iyonlaşma enerjisi azalır." },
  { id: "q_yk2_4", capsuleId: "yk2", category: "kimya", question: "Bir katyonun (pozitif iyon) yarıçapı, oluştuğu atoma göre nasıldır?", options: ["Daha büyüktür", "Daha küçüktür", "Eşittir", "İki katıdır"], correctIndex: 1, explanation: "Katyon elektron kaybettiği için yarıçapı, nötr atomundan daha küçüktür." },

  // yb1 Kalıtım problemleri
  { id: "q_yb1_1", capsuleId: "yb1", category: "biyoloji", question: "Aa × Aa çaprazlamasında oluşacak döllerin fenotip oranı nedir? (A baskın)", options: ["1:1", "3:1", "9:3:3:1", "1:2:1"], correctIndex: 1, explanation: "Aa × Aa → 1 AA, 2 Aa, 1 aa. Baskın fenotip : çekinik fenotip = 3:1'dir." },
  { id: "q_yb1_2", capsuleId: "yb1", category: "biyoloji", question: "AB kan grubu, kalıtımda hangi kavramın klasik örneğidir?", options: ["Tam baskınlık", "Eş baskınlık (eş dominantlık)", "Çekiniklik", "Eşeye bağlılık"], correctIndex: 1, explanation: "A ve B alelleri eş baskındır; ikisi bir arada bulununca her ikisi de fenotipte görünür (AB grubu)." },
  { id: "q_yb1_3", capsuleId: "yb1", category: "biyoloji", question: "X'e bağlı çekinik hastalıklar (renk körlüğü, hemofili) neden erkeklerde daha sıktır?", options: ["Erkeklerde iki X vardır", "Erkeklerde tek X olduğu için çekinik alel doğrudan ortaya çıkar", "Y kromozomu baskındır", "Erkekler daha çok mutasyona uğrar"], correctIndex: 1, explanation: "Erkekte tek X bulunduğundan, X üzerindeki çekinik alel eşleşecek ikinci bir alel olmadığı için doğrudan fenotipe yansır." },
  { id: "q_yb1_4", capsuleId: "yb1", category: "biyoloji", question: "Bir soy ağacında sağlıklı anne-babadan etkilenmiş bir çocuk doğmuşsa, bu özellik büyük olasılıkla nasıldır?", options: ["Baskındır", "Çekiniktir", "Eşeye bağlı baskındır", "Belirlenemez"], correctIndex: 1, explanation: "Etkilenmemiş ebeveynlerden etkilenmiş çocuk çıkması, gizli çekinik alellerin birleştiğini gösterir; özellik çekiniktir." },

  // yb2 Enzimler
  { id: "q_yb2_1", capsuleId: "yb2", category: "biyoloji", question: "Sıcaklık optimum değeri geçtikten sonra enzim hızı neden hızla düşer?", options: ["Substrat biter", "Enzim yapısı bozulur (denatürasyon)", "pH değişir", "Enzim çoğalır"], correctIndex: 1, explanation: "Yüksek sıcaklık enzimin protein yapısını bozar (denatürasyon), bu yüzden hız hızla düşer." },
  { id: "q_yb2_2", capsuleId: "yb2", category: "biyoloji", question: "Substrat derişimi sürekli artırılırsa enzim hızı grafiği ne yapar?", options: ["Sürekli artar", "Belirli noktadan sonra düzleşir (plato)", "Sıfıra iner", "Ani düşer"], correctIndex: 1, explanation: "Tüm enzimler substratla dolunca (doyunca) hız sabitlenir; grafik plato yapar." },
  { id: "q_yb2_3", capsuleId: "yb2", category: "biyoloji", question: "Enzimlerin substrata özgü çalışmasını açıklayan model hangisidir?", options: ["Baloncuk modeli", "Anahtar-kilit modeli", "Zincir modeli", "Kafes modeli"], correctIndex: 1, explanation: "Her enzim yalnızca kendi substratına uyar; bu özgüllük anahtar-kilit modeliyle açıklanır." },
  { id: "q_yb2_4", capsuleId: "yb2", category: "biyoloji", question: "Sıcaklık grafiği optimumdan sonra düşerken, substrat derişimi grafiği düzleşir. Bu farkın nedeni nedir?", options: ["İkisi de aynı davranır", "Sıcaklıkta enzim bozulur, substratta enzim doyar (bozulmaz)", "Substratta enzim bozulur", "Sıcaklıkta substrat biter"], correctIndex: 1, explanation: "Sıcaklık grafiği denatürasyon nedeniyle düşer; substrat grafiği ise enzimler doyduğu için düzleşir (bozulma yoktur)." },

  // yh1 Kurtuluş Savaşı kronolojisi
  { id: "q_yh1_1", capsuleId: "yh1", category: "tarih", question: "Milletin bağımsızlığını yine milletin sağlayacağını ilk kez duyuran belge hangisidir?", options: ["Erzurum Kongresi", "Amasya Genelgesi", "Sivas Kongresi", "Misak-ı Milli"], correctIndex: 1, explanation: "Amasya Genelgesi, kurtuluşun milletin azim ve kararıyla sağlanacağını ilk kez ilan eden belgedir." },
  { id: "q_yh1_2", capsuleId: "yh1", category: "tarih", question: "Kurtuluş Savaşı'nda savunmadan taarruza geçişin dönüm noktası sayılan savaş hangisidir?", options: ["I. İnönü", "II. İnönü", "Sakarya Meydan Muharebesi", "Büyük Taarruz"], correctIndex: 2, explanation: "Sakarya Meydan Muharebesi (1921) dönüm noktasıdır; bu zaferden sonra Mustafa Kemal'e 'Gazi' unvanı ve mareşallik verilmiştir." },
  { id: "q_yh1_3", capsuleId: "yh1", category: "tarih", question: "Ulusal egemenliğin fiilen gerçekleştiği olay hangisidir?", options: ["Mondros Ateşkesi", "TBMM'nin açılışı (23 Nisan 1920)", "Lozan Antlaşması", "Mudanya Ateşkesi"], correctIndex: 1, explanation: "23 Nisan 1920'de TBMM'nin açılmasıyla egemenlik millete geçmiş, ulusal egemenlik fiilen kurulmuştur." },
  { id: "q_yh1_4", capsuleId: "yh1", category: "tarih", question: "Yeni Türk Devleti'nin bağımsızlığının uluslararası alanda tescillendiği antlaşma hangisidir?", options: ["Gümrü Antlaşması", "Mudanya Ateşkesi", "Lozan Antlaşması", "Ankara Antlaşması"], correctIndex: 2, explanation: "Lozan Antlaşması (1923) ile Türkiye'nin bağımsızlığı ve sınırları uluslararası alanda kabul edilmiştir." },

  // yh2 Osmanlı yönetim
  { id: "q_yh2_1", capsuleId: "yh2", category: "tarih", question: "Osmanlı'da devlet işlerinin görüşülüp karara bağlandığı kurul hangisidir?", options: ["Divan-ı Hümayun", "Enderun", "Lonca", "Sekban"], correctIndex: 0, explanation: "Divan-ı Hümayun, önemli devlet işlerinin görüşülüp karara bağlandığı en yüksek yönetim kuruludur." },
  { id: "q_yh2_2", capsuleId: "yh2", category: "tarih", question: "Tımar sisteminde devlet, toprağın gelirini kime, ne karşılığında verirdi?", options: ["Halka, vergi karşılığında", "Sipahiye, asker yetiştirme hizmeti karşılığında", "Tüccara, ticaret karşılığında", "Din adamlarına, eğitim karşılığında"], correctIndex: 1, explanation: "Tımar sisteminde miri arazinin geliri, asker (tımarlı sipahi) yetiştirme hizmeti karşılığında sipahilere verilirdi." },
  { id: "q_yh2_3", capsuleId: "yh2", category: "tarih", question: "Osmanlı'da gayrimüslimlere dinî ve hukukî özerklik tanıyan yapı hangisidir?", options: ["Tımar sistemi", "Millet sistemi", "Lonca sistemi", "Devşirme sistemi"], correctIndex: 1, explanation: "Millet sistemi, farklı din ve mezheplere mensup toplulukların kendi iç işlerinde özerk olmasını sağlardı." },
  { id: "q_yh2_4", capsuleId: "yh2", category: "tarih", question: "Tımar sisteminin bozulması Osmanlı'da hangi alanları aynı anda olumsuz etkilemiştir?", options: ["Yalnızca eğitim", "Tarımsal üretim ve ordu düzeni", "Yalnızca ticaret", "Yalnızca sanat"], correctIndex: 1, explanation: "Tımarın bozulması hem tarımsal üretimi hem tımarlı sipahiye dayalı ordu düzenini birlikte sarsmış, zincirleme bir çöküşe yol açmıştır." },

  // yc1 Sıcaklık-yükselti
  { id: "q_yc1_1", capsuleId: "yc1", category: "cografya", question: "Türkiye'de en düşük sıcaklıkların Doğu Anadolu'da görülmesinin temel nedeni nedir?", options: ["Kuzeyde olması", "Yükseltinin fazla olması", "Denize yakın olması", "Ormanların çokluğu"], correctIndex: 1, explanation: "Doğu Anadolu'nun ortalama yükseltisi çok fazladır; yükselti etkisi enlem etkisini bastırarak sıcaklığı düşürür." },
  { id: "q_yc1_2", capsuleId: "yc1", category: "cografya", question: "Yükselti her 100 metre arttığında sıcaklık ortalama nasıl değişir?", options: ["0,5°C artar", "0,5°C azalır", "5°C azalır", "Değişmez"], correctIndex: 1, explanation: "Troposferde yükseldikçe sıcaklık her 100 metrede ortalama 0,5°C azalır." },
  { id: "q_yc1_3", capsuleId: "yc1", category: "cografya", question: "Kıyı bölgelerin iç bölgelere göre yıllık sıcaklık farkının az olmasının nedeni nedir?", options: ["Yükseltilerinin fazla olması", "Denizin ılımanlaştırıcı etkisi", "Enlemlerinin farklı olması", "Bitki örtüsünün az olması"], correctIndex: 1, explanation: "Deniz, yavaş ısınıp yavaş soğuyarak kıyıları ılımanlaştırır; bu yüzden kıyıda yıllık sıcaklık farkı azdır (denizellik)." },
  { id: "q_yc1_4", capsuleId: "yc1", category: "cografya", question: "Kuzey yarım kürede güneş ışınlarını daha dik alan ve daha sıcak olan yamaç hangisidir?", options: ["Kuzey (bakısı gölgeli) yamaç", "Güney yamaç", "Batı yamaç", "Doğu yamaç"], correctIndex: 1, explanation: "Kuzey yarım kürede güneşe dönük olan güney yamaçlar ışınları daha dik alır ve daha sıcaktır (bakı etkisi)." },

  // yc2 Nüfus piramitleri
  { id: "q_yc2_1", capsuleId: "yc2", category: "cografya", question: "Geniş tabanlı (üçgen) bir nüfus piramidi neyi gösterir?", options: ["Yaşlanan, gelişmiş ülke", "Genç ve hızla artan nüfus, az gelişmiş ülke", "Nüfusu azalan ülke", "Eşit dağılımlı nüfus"], correctIndex: 1, explanation: "Geniş taban, yüksek doğum oranını ve genç, hızla artan nüfusu; bu da genellikle az gelişmiş ülkeyi gösterir." },
  { id: "q_yc2_2", capsuleId: "yc2", category: "cografya", question: "Nüfus piramidinin tabanının daralması neyi ifade eder?", options: ["Ölüm oranının arttığını", "Doğum oranının düştüğünü", "Göçün arttığını", "Yaşam süresinin kısaldığını"], correctIndex: 1, explanation: "Tabandaki daralma, doğan çocuk sayısının, yani doğum oranının azaldığını gösterir." },
  { id: "q_yc2_3", capsuleId: "yc2", category: "cografya", question: "Yaşlanan (dar tabanlı piramide sahip) gelişmiş ülkeler genellikle nasıl bir nüfus politikası uygular?", options: ["Nüfus artışını yavaşlatıcı", "Doğumu teşvik edici (artırıcı)", "Göçü yasaklayıcı", "Politika uygulamaz"], correctIndex: 1, explanation: "Yaşlanan nüfusa sahip ülkeler iş gücü ve genç nüfus için doğumu teşvik edici (artırıcı) politikalar uygular." },
  { id: "q_yc2_4", capsuleId: "yc2", category: "cografya", question: "Bir nüfus piramidinin tabanındaki ani 'çentik' (daralma) hangi durumu gösterebilir?", options: ["Bolluk dönemi", "Savaş, salgın veya ekonomik kriz nedeniyle doğumların düştüğü dönem", "Göç dalgası", "Sanayileşme"], correctIndex: 1, explanation: "Belirli bir yaş grubundaki ani daralma, o dönemde doğumları azaltan savaş, salgın veya kriz gibi bir olayı işaret eder." },

  // ye1 Söz sanatları
  { id: "q_ye1_1", capsuleId: "ye1", category: "edebiyat", question: "'Menekşeler başlarını öne eğmiş bizi selamlıyordu.' dizesinde hangi söz sanatı vardır?", options: ["Teşbih", "Teşhis (kişileştirme)", "Kinaye", "Mecaz-ı mürsel"], correctIndex: 1, explanation: "Menekşelere 'selamlama' gibi insana özgü bir eylem verildiği için teşhis (kişileştirme) yapılmıştır." },
  { id: "q_ye1_2", capsuleId: "ye1", category: "edebiyat", question: "Benzetmenin yalnızca benzetilen ögesiyle yapılmasına ne ad verilir?", options: ["Açık istiare", "Kapalı istiare", "Teşbih-i beliğ", "Tezat"], correctIndex: 0, explanation: "Sadece benzetilenin söylendiği (benzeyenin gizlendiği) istiare açık istiaredir: 'Havada uçan aslanları izledik' (aslan = kartal)." },
  { id: "q_ye1_3", capsuleId: "ye1", category: "edebiyat", question: "'Ankara bu konuda açıklama yaptı.' cümlesinde hangi söz sanatı vardır?", options: ["Teşbih", "Teşhis", "Mecaz-ı mürsel (ad aktarması)", "Kinaye"], correctIndex: 2, explanation: "'Ankara' sözüyle başkent değil, hükümet kastedilmiştir; benzetme amacı olmadan yapılan bu aktarma mecaz-ı mürseldir." },
  { id: "q_ye1_4", capsuleId: "ye1", category: "edebiyat", question: "Bir sözün hem gerçek hem mecaz anlama gelebilecek biçimde, asıl mecazı kastederek kullanılmasına ne denir?", options: ["Kinaye", "Teşbih", "İntak", "Tezat"], correctIndex: 0, explanation: "Kinayede söz gerçek anlamıyla da düşünülebilir ama asıl mecaz anlam kastedilir: 'Onun eli açıktır' (cömerttir)." },

  // ye2 Edebî dönemler
  { id: "q_ye2_1", capsuleId: "ye2", category: "edebiyat", question: "'Aşk-ı Memnu' romanının yazarı ve dönemi hangisidir?", options: ["Halit Ziya Uşaklıgil - Servet-i Fünun", "Namık Kemal - Tanzimat", "Ömer Seyfettin - Millî Edebiyat", "Orhan Veli - Cumhuriyet"], correctIndex: 0, explanation: "'Aşk-ı Memnu', Servet-i Fünun döneminin sanatçısı Halit Ziya Uşaklıgil'in eseridir ve ilk modern Türk romanı sayılır." },
  { id: "q_ye2_2", capsuleId: "ye2", category: "edebiyat", question: "Türk edebiyatındaki ilk yerli roman hangisidir?", options: ["Telemak", "Taaşşuk-ı Talat ve Fitnat", "Araba Sevdası", "İntibah"], correctIndex: 1, explanation: "İlk yerli roman Şemsettin Sami'nin 'Taaşşuk-ı Talat ve Fitnat'ıdır; 'Telemak' ise ilk çeviri romandır." },
  { id: "q_ye2_3", capsuleId: "ye2", category: "edebiyat", question: "Sade dil ve hece ölçüsünü benimseyen, halk kaynaklarına yönelen dönem hangisidir?", options: ["Servet-i Fünun", "Millî Edebiyat", "Tanzimat II. dönem", "Fecr-i Âti"], correctIndex: 1, explanation: "Millî Edebiyat akımı sade dili, hece ölçüsünü ve halk/millî kaynaklara dönüşü benimsemiştir." },
  { id: "q_ye2_4", capsuleId: "ye2", category: "edebiyat", question: "Fecr-i Âti'den başlayıp Millî Edebiyat ve Cumhuriyet romanına geçen, birden çok dönemde yer alan sanatçı kimdir?", options: ["Yakup Kadri Karaosmanoğlu", "Şinasi", "Fuzûlî", "Karacaoğlan"], correctIndex: 0, explanation: "Yakup Kadri, Fecr-i Âti'de başlayıp Millî Edebiyat'a ve Cumhuriyet Dönemi romanına geçen; bir sanatçının birden çok dönemde bulunabileceğinin klasik örneğidir." },
];
